### ISSUE TITLE
Public Access to Mouse Events

### ISSUE THREAD

**Issue by dani-h** [alexandersimoes/d3plus#140]
D3 has the .on("click|hover|..") functionality that let's you define custom actions on click. In my particular case I need a ajax post to reload data or a async reload if d3plus supports it. (The request needs to be sent to the server which responds with new data, but I only need the click functionality to solve the rest).

**Comment by dani-h** [comment]
What happened ever happened to this request :] ?

@davelandry Do you have a custom click method? Attaching events to the d3 el will return the native browser event or the jquery wrapper around it. Nothing that will link you to the old element. The solution is still monkey patching the rects to include some sort of identifiers and then finding the components in your own cache.

**Comment by davelandry** [comment]
I didn't forget about you! :wink: 

I'm prioritizing this issue. It will be a part of version 1.7 :-)

**Comment by dani-h** [comment]
:+1: :+1: :+1: 

Side note: Seeing as you were pretty flexible with alternatives to javascript you should look at Typescript. A large project like this with some typing hints gives killer IDE features (Webstorm/Pycharm/Eclipse/Visual Studio).
 
I've started working a on a d3.d.ts (typescript definition) file for my own use, but it takes time to cover all of the d3plus features. I'll push it upstream (https://github.com/borisyankov/DefinitelyTyped)  when I have more stuff finished. You could look at it then.

**Comment by jazzido** [comment]
+1 to this. I'm currently working around the limitation with a jQuery delegated event handler:

```javascript
    $('#treemap').on(
        {
            mouseover: function(o) {
                console.log(this.__data__);
            }
        }, 'g.d3plus_rect rect');
```

**Comment by jmls** [comment]
did events make it into 1.7 ? /me looking at the 1.7.4 release ...

**Comment by davelandry** [comment]
Nope, not in 1.7.

**Comment by jmls** [comment]
bugger. :( 
any idea when ?

**Comment by dchersey** [comment]
+1 on this for histograms!

**Comment by davelandry** [comment]
Done. This will be part of 1.8, which I'll be releasing in the next couple of days (along with documentation for how to use this).

I just want to take a second to thank everyone in this thread for showing their interest. There's so many cool things we want to do in D3plus, and we love prioritizing things based on what the community needs.

:beers:

**Comment by dchersey** [comment]
Terrific! Was just hacking through a way in doing this with Jquery … I will happily wait for (and help test) the new feature & documentation. 

It’s wonderful when the community comes together to support what we are all trying to accomplish with visualization — and d3plus is a perfect example of the type of enabling technology that can help us all achieve our goals.  Loving it!

David

**Comment by dani-h** [comment]
:+1:

**Comment by davelandry** [comment]
It's released! Here's the note: https://github.com/alexandersimoes/d3plus/releases/tag/v1.8.0

And the full documentation: https://github.com/alexandersimoes/d3plus/wiki/Visualizations#mouse

**Comment by jazzido** [comment]
👏

**Comment by dchersey** [comment]
(possibly dumb) question — I am using this new feature on a Histogram, and when I use the following code: 

 var histogram = d3plus.viz()
              .container("#histogram")
              .data(initiatives)
              .type("bar")
              .id("name")
              .y("name")
              .y({"scale": "discrete", "grid": false, "label": false}) 
              .x("initiatives")
              .color("color")
              .order("initiatives-inv")
              .legend(false)
              .labels(false)
              .width(500)
              .height(750)
              .mouse(handleClick)
              .draw();

    function handleClick(data, d3) {
            console.log('click');   
    }


I get the following error: 


"undefined" is not an accepted value for .mouse(), please use one of the following: Boolean.

Am I passing the function correctly?  I am trying to intercept the click event and initiate a navigation. 

Thanks!

David

**Comment by davelandry** [comment]
You have to explicitly pass your function to the "click" parameter of .mouse( ). The release notes have an example: https://github.com/alexandersimoes/d3plus/releases/tag/v1.8.0

**Comment by dchersey** [comment]
Ah, thanks!

**Comment by kasram** [comment]
I have a bubble map that I want to click on a bubble and return a value. I have a Userid as the ID and a quantity of messages sent as the size. How can I return the value of the ID through a click event? Generally how can I access the data?

**Comment by davelandry** [comment]
@kasram take a look at the example in the release notes: https://github.com/alexandersimoes/d3plus/releases/tag/v1.8.0

The variable "d" that is passed to the function is the data point of the clicked circle.

**Comment by tmthyjames** [comment]
is there a way to simulate a mouse event? for example, i have an input form that i want to bind a d3plus mouse event to.
