### ISSUE TITLE
Implement Zooming for Chart Visualization

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#21]
Example: http://bl.ocks.org/stepheneb/1182434

**Comment by aswinm** [comment]
Is this implemented? Adding `zoom()` function to my d3plus line plot does not work :( 
please update the status of this feature @davelandry

**Comment by davelandry** [comment]
@aswinm we'll be implementing this as part of the 2.0 modules, I've created an issue to track it here: https://github.com/d3plus/d3plus-plot/issues/57
