### ISSUE TITLE
Window is not defined error in nodejs

### ISSUE THREAD

**Issue by yang-wei** [alexandersimoes/d3plus#226]
I want to use d3plus in my server side js but I get this error. 

```
var d3 = require('d3')
var d3plus = require('d3plus')

var tree = ...

module.exports = tree;
```

![windowisnotdefined](https://cloud.githubusercontent.com/assets/5494874/5352654/ef1ce410-7fad-11e4-802a-9c2aa3e893a7.png)

Is that a way to overcome this error without modifying d3plus.js.

**Comment by heenamahour** [comment]
@davelandry is d3plus usable at server side ? If so, could you provide a sample fiddle for the same :)

**Comment by davelandry** [comment]
@heenamahour sorry, I don't have any experience trying to use it server-side 😢
