### ISSUE TITLE
Network Node Label Vertical Alignment

### ISSUE THREAD

**Issue by kevinzenghu** [alexandersimoes/d3plus#228]
When using certain fonts (Open Sans Condensed or Oswald) the node labels are vertically aligned towards the top of the node. Is there an argument I can pass to .labels() to adjust this alignment?

![screen shot 2014-12-12 at 1 30 41 pm](https://cloud.githubusercontent.com/assets/1390391/5416991/16add5be-8203-11e4-937f-ef8bf1e71e53.png)

**Comment by davelandry** [comment]
@kevinzenghu, this should be all set in the next release.

**Comment by kevinzenghu** [comment]
Woo hoo, thanks @davelandry!
