### ISSUE TITLE
Vertical/Horizontal Centering Wrapped Text

### ISSUE THREAD

**Issue by superdudeboy** [alexandersimoes/d3plus#236]
See http://jsfiddle.net/zrzx5Lvu/3/ for examples of the result I'm looking for. 

It would be real nice to be able to set the alignment of wrapped text, especially being able to center the text in a rectangle, both horizontally and vertically. Maybe by setting class attribute in the HTML, or doing it by code like below for example. 

d3plus.textwrap()
    .container(d3.select("#rectWrap3"))
    .verticalAlign("middle")
    .draw();

For horizontal centering, you can add "text-anchor: middle" to the style and set all tspan's x values to x value of the rect's x value and add half of the shapes's width:
all tspan dx values = rect's x position + (rect's width / 2)

Vertical centering seems more tricky, I'm not sure how to do it properly, but it seems to work ok by setting the dy value of the first tspan with the below formula:
first tspan dy value = (rect's height / 2) - (sum of remaining tspan's dy values / 2)

Combine both to have the text centered in the middle of the rectangle.

The jsfiddle link above shows examples with the final result after applying text-anchor and tspan calculations.

**Comment by davelandry** [comment]
Added .align( ) and .valign( ) methods to d3plus.textwrap(). I will document these with the next release.

**Comment by superdudeboy** [comment]
Awesome, thanks! I can't get it working with the latest version, I guess this hasn't been released yet? Any plans on when to release?

**Comment by davelandry** [comment]
I'm hoping to release v1.6.9 this week, but in the meanwhile I've compiled a development build in the main repo if you want to grab that!

**Comment by superdudeboy** [comment]
Thanks. I tried it with the new version (the one at https://github.com/alexandersimoes/d3plus/blob/master/d3plus.js to be exact) but the results are not looking right, even without using the align() and valign() methods. Some of the text disappears. See screenshots below. I dumped the code I used here: http://pastebin.com/ViBuuiaT#

**Old version:**
![original](https://cloud.githubusercontent.com/assets/10222524/5716943/329eb83e-9af8-11e4-90d6-b1b6121de5e3.PNG)

**New version (identical code to above, without using align() or valign()):**
![new](https://cloud.githubusercontent.com/assets/10222524/5716947/59c81554-9af8-11e4-8f5c-d9f2803e7456.PNG)

The align() and valign() methods also breaks the wrapping but that might be me using it wrong. I've tried it like below, is this right?

`d3plus.textwrap()`
    `.container(d3.select("#rectWrap"))`
    `.valign()`
    `.draw();`

**Comment by davelandry** [comment]
I will be documenting all of the changes and creating a new example page when the new version is released, but for now:
* .align( ) accepts "left", "center", or "right"
* .valign( ) accepts "top", "middle", "bottom"
* if a "dy" attribute of the text block is defined, it now uses that as line-spacing

And as always, I'll be bug testing this a bit more before release.

**Comment by superdudeboy** [comment]
Great, thanks for info! Will try some more.

**Comment by superdudeboy** [comment]
I've done some more testing. align() and valign() works great!

I found that text seems to disappear in the new version when the x-coordinate of the shape is not the same as the x-coordinate of the text. I don't know if this is a bug or some kind of design change?

**Works**
 `<rect class="shape" height="150px" width="450px" y="400px" x="400px"></rect>`	
  `<text id="rectWrap3" class="wrap" dy="12" height="150px" width="350px" x="400px" y="400px" font-size="12">`
    `Here is a long text string that SVG should wrap by default, but it does not. Here is a long text string that SVG should wrap by default, but it does not. Here is a long text string that SVG should wrap by default, but it does not.`
 ` </text> `

**Does not work, text disappears**
 `<rect class="shape" height="150px" width="450px" y="400px" x="400px"></rect>`	
  `<text id="rectWrap3" class="wrap" dy="12" height="150px" width="350px" x="500px" y="400px" font-size="12">`
    `Here is a long text string that SVG should wrap by default, but it does not. Here is a long text string that SVG should wrap by default, but it does not. Here is a long text string that SVG should wrap by default, but it does not.`
 ` </text> `

**Comment by davelandry** [comment]
That is because d3plus uses the x/y position of the text in relation to the rectangle's x/y to figure out padding (which can also be set with the new .padding( )). If you make the change the coordinates to `x="410px" y="410px"` you'll see it working with padding.

**Comment by davelandry** [comment]
v1.6.9 has been released! The new features are documented here: https://github.com/alexandersimoes/d3plus/wiki/Text%20Wrapping

I'll be making an advanced text wrap example showing all of the new features (#246).

**Comment by superdudeboy** [comment]
Thanks! Life is now easier.
