### ISSUE TITLE
albersUsa Geo Map Projection

### ISSUE THREAD

**Issue by ltoole** [alexandersimoes/d3plus#240]
I want to create a geomap of the USA using D3plus. I want to show Alaska and Hawaii below the SW part of lower 48 states using the d3.geo.albersUsa d3 projection. However, it does not look like d3plus supports this. I tried setting "projection" key in .coords to "albersUsa", but desired projection was not rendered.

**Comment by ltoole** [comment]
Any status update on supporting the albersUsa projection? I'm doing a bunch of Affordable Care Act map visualizations and it would really be helpful to have Alaska and Hawaii shown on map with this type of projection.

**Comment by davelandry** [comment]
We still haven't looked into this. We're in the process of re-tooling how a lot of the internals work, including Geo Map, and we'll look into this once we're at that stage.
