### ISSUE TITLE
Add to cdnjs.com

### ISSUE THREAD

**Issue by neothemachine** [alexandersimoes/d3plus#242]
This library should be added to cdnjs.com! See https://github.com/cdnjs/cdnjs for instructions.

**Comment by davelandry** [comment]
I just created the pull request to include D3plus in cdnjs, you can follow the progress here: https://github.com/cdnjs/cdnjs/pull/4174

I'll close this issue once it goes live.

**Comment by neothemachine** [comment]
Thanks!
