### ISSUE TITLE
SyntaxError: Line 2: Unexpected token ILLEGAL while parsing …/node_modules/d3plus/src/init.coffee

### ISSUE THREAD

**Issue by vid** [alexandersimoes/d3plus#244]
congrats on the new release. however  I'm getting this when I try to include from my nodejs project:

`var d3plus = require('d3plus');`

…

`SyntaxError: Line 2: Unexpected token ILLEGAL while parsing …/node_modules/d3plus/src/init.coffee while parsing file:…/node_modules/d3plus/src/init.coffee`

**Comment by davelandry** [comment]
Good catch, this is fixed for the next release. Sorry about that.

**Comment by vid** [comment]
np and thanks!
