### ISSUE TITLE
Text doesn't wrap right in IE9

### ISSUE THREAD

**Issue by superdudeboy** [alexandersimoes/d3plus#251]
The text wrapping feature doesn't seem to work quite right in IE9. The wrapping area goes outside the rectangle. When aligned on the top it also appears slightly above the recangle (this can be seen on your own example page with IE9). 

**Chrome**
![chrome](https://cloud.githubusercontent.com/assets/10222524/5899934/0e27a43c-a563-11e4-801b-a611f0aa316c.PNG)

**vs. IE9**
![ie9](https://cloud.githubusercontent.com/assets/10222524/5899933/0e1fe4fe-a563-11e4-8608-dfff883c33a8.PNG)
![ie9b](https://cloud.githubusercontent.com/assets/10222524/5899980/840c7b1e-a563-11e4-9379-377b89c62c58.PNG)

**Comment by davelandry** [comment]
Was an issue with IE not supporting the SVG properties "baseline-shift" and "dominant-baseline"

**Comment by superdudeboy** [comment]
Goody! Any chance you can compile an early version with the fix?

**Comment by davelandry** [comment]
:guitar: DONE

**Comment by superdudeboy** [comment]
Thanks! That version broke the wrapping for me though. d3plus.js is also 5 megs large, which is a bit peculiar.

**Comment by davelandry** [comment]
Strange, my version (and the version in the repo) is 955kb. Where are you getting d3plus.js from?

Also, can you post a snippet of your code that isn't working with the text wrapping?

**Comment by superdudeboy** [comment]
Sorry I'm just an idiot and had downloaded it wrong. 

Now my problem is that the text disappears in completely in IE9 instead, maybe hiding under the rectangles. It may be a problem in my own HTML, I'll look into it more tomorrow.

**Comment by superdudeboy** [comment]
I can't see what the problem is. The code in the link below work fine when running in jsfiddle in IE9, but not when I put in an html file and open it in IE9. Then there's no text. 

![rect](https://cloud.githubusercontent.com/assets/10222524/5939527/d263dce2-a704-11e4-8d29-b51a573c261b.PNG)

http://jsfiddle.net/5c9115nh/

Bug? Or some local problem of mine?

**Comment by davelandry** [comment]
Whoops, seems that IE9 can't handle setting "style" for dominant-baseline. It strictly needs to be an "attr". I just pushed this fix, along with new dev builds.

**Comment by superdudeboy** [comment]
Thanks, works nicely now. Now I've found another smaller IE9 bug that I'll post as a separate issue.
