### ISSUE TITLE
AngularJS directives for d3plus charts

### ISSUE THREAD

**Issue by madasuk** [alexandersimoes/d3plus#255]
Is there any possibilities of releasing Angularjs directives for d3plus charts?

**Comment by davelandry** [comment]
Of course that's a possibility! Although we don't have much (if any) experience with AngularJS. Could recommend some documentation/tutorials and explain how you personally would like to see it implemented?

**Comment by madasuk** [comment]
Thanks Davelandry for the response. Till now for the normal charts (line, bar, etc) I am using c3.js (http://c3js.org/) which is a simple but very powerful library and its angularjs directives can be found at https://github.com/wasilak/angular-c3-simple. The main drawback I am facing with C3.js is, I can't use this library to draw charts of my preference, I need to manage my requirements with in the available charts at C3.js (http://c3js.org/examples.html). For example, now I had requirements for Zoomable Sunburst (http://bl.ocks.org/kerryrodden/477c1bfb081b783f80ad), Heat Map (http://jsfiddle.net/indiemaps/gzPDU/), Zoomable Circle Packing chart (http://bl.ocks.org/mbostock/7607535), Co-occurrence Matrix (http://bost.ocks.org/mike/miserables/). So in my search to meet requirements I have come across d3 plus. With the experience I had, I noticed d3 plus is also very simple library like that of c3.js. I would like to know whether these charts can be easily implemented in d3plus? The angular js directives for d3plus should be developed in such a way in future   even if we want some of the new type of charts from Mike Bostock d3.js example, we should be able to easily handle it. I am feeling that meeting this type of requirement  make d3plus unique library and fills the gap with the available d3/angularjs charting libraries. Please let me know if you want me to make any further clarification on this. For normal line, bar, etc for now I am quiet satisfied with c3.js and does not feel any need to migrate to another library.

**Comment by mariohmol** [comment]
still pending? i'm planning to make it

**Comment by mariohmol** [comment]
here is a first version... now basically need to match all chart types and vars

https://github.com/mariohmol/angular-d3plus/

**Comment by davelandry** [comment]
@mariohmol my hero! great work

**Comment by mariohmol** [comment]
i updated with a new version and almost all chart types with a working example.. 

now i'm going to use this in one project.. so i will keep working on it

you may close the issue! =)

**Comment by davelandry** [comment]
@mariomol: 🍻
