### ISSUE TITLE
cannot find a container on the page matching ""

### ISSUE THREAD

**Issue by bobiblazeski** [alexandersimoes/d3plus#258]
I got hundreds of weird messages in my console from d3plus though all my charts are removed from the current page.
  
cannot find a container on the page matching "".
d3plus.full.min.js:10 line 17881) of simoes_d3plus.js?886b3496825d338d84f2c7b893ac1de239aab6e1:43: Function.57.a.stack (http://localhost:3000/packages/simoes_d3plus.js?886b3496825d338d84f2c7b893ac1de239aab6e1:43:17881)
d3plus.full.min.js:10 documentation: https://github.com/alexandersimoes/d3plus/wiki/Container-Element

![d3plus](https://cloud.githubusercontent.com/assets/2140890/5984035/ad6a7002-a8d2-11e4-8aef-fae09c974320.png)

I have a meteor single page application and I'm in a route that doesn't have any d3plus visualization, the charts are at the other routes.

**Comment by joaom182** [comment]
Hello @bobiblazeski, you discovered any workarround?

**Comment by aandis** [comment]
Facing this.

**Comment by bobiblazeski** [comment]
@joaom182 I believe rewrote the application somewhat later using React and I didn't had the problem anymore. Sorry I can't be more specific it has been a long time.

**Comment by aandis** [comment]
I am using ember and this is happening even with latest version.

**Comment by aandis** [comment]
A script deep down somewhere was modifying the `id` due to which d3plus couldn't find the specified element. I think the error message should be corrected to say 

> cannot find a container on the page matching <id>

Without that, it just looks like it's a bug in d3plus itself.
