### ISSUE TITLE
Custom time formatting not working

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#259]
http://plnkr.co/edit/3Fbi1fabPK0Sso7zuj7s?p=preview

**Comment by davelandry** [comment]
.time( ) now accepts custom formatting, in three different ways. Passing a custom format string:
```js
.time({"format": "%A"})
```

Passing a D3 format function:
```js
.time({"format": d3.time.format("%A")})
```

Or passing a [multi-format](https://github.com/mbostock/d3/wiki/Time-Formatting#format_multi) array:
```js
.time({"format": [
    [".%L", function(d) { return d.getMilliseconds(); }],
    [":%S", function(d) { return d.getSeconds(); }]
]})
```

**Comment by freezepl** [comment]
Thanks!
