### ISSUE TITLE
Line Plot date axis bugs

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#260]
http://plnkr.co/edit/3Fbi1fabPK0Sso7zuj7s?p=preview

**Comment by davelandry** [comment]
Another problem: http://plnkr.co/edit/ebthy5tDLcOHZ4jcuZ4f?p=preview

**Comment by freezepl** [comment]
When this will be available in dev build?

**Comment by davelandry** [comment]
Just compiled, available in the main repo.

**Comment by freezepl** [comment]
So I ran new code (copied it to file) and I have trouble with visualization that worked before, and now i doesn't:

http://plnkr.co/edit/YEdcXbVzovDkyJBiZRPx?p=preview
On the top you have commented link to d3plus release.

Thanks

**Comment by davelandry** [comment]
Can you please create a new issue for this bar chart example?

**Comment by davelandry** [comment]
Conversation continued here: #269
