### ISSUE TITLE
Bar plot - Discrete Y-axis broken

### ISSUE THREAD

**Issue by freezepl** [alexandersimoes/d3plus#269]
I was testing newest code, and I see it breaks bar plots which works on 1.6.9

http://jsbin.com/mewijifeya/1/edit?html,output

In the header you have current release js commented out.

Thanks!

**Comment by freezepl** [comment]
Problem still exists on new build.

**Comment by davelandry** [comment]
Some of my recent code actually introduced a new error having to do with bar ordering. See if the new dev build works for you now.

**Comment by freezepl** [comment]
Works great! thanks!
