### ISSUE TITLE
Click-zoom not working when only 1 child element

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#270]
Submitted from the Google Group: https://groups.google.com/forum/#!topic/d3plus/wtDes2w86sI

**Comment by metasyn** [comment]
+1

**Comment by metasyn** [comment]
This should maybe reopen #66 ?

**Comment by davelandry** [comment]
I'm thinking of adding 2 solutions for this:
 * Always allow click-zoom when the next level is not the deepest.
 * Create a toggle for this behavior, which I think should be turned off by default (to always allow clicking).

Again, sorry about the confusing codebase. We're currently taking a deep look at the code is structured to aid better collaboration.
