### ISSUE TITLE
Sizing of geomap is different after new version release

### ISSUE THREAD

**Issue by ltoole** [alexandersimoes/d3plus#271]
I tried using the new version of d3plus, but had to go back to older version because my geomap no longer sizes correctly on load. 

Here is load of geomap with previous version...

![image](https://cloud.githubusercontent.com/assets/6303114/6360814/184896ac-bc4b-11e4-99bf-f3ce629f5115.png)

And here is load of geomap with new version...

![image](https://cloud.githubusercontent.com/assets/6303114/6360838/3ebe6c3a-bc4b-11e4-9030-9dd2ff04a640.png)

My javascript code:

var visualization = d3plus.viz()
                              .container("#viz")        // container DIV to hold the visualization
                              .data(data.geodata)        // data to use with the visualization
                              .coords({"value": topofile, "mute": [15001, 15003, 15005, 15007, 15009, 2013, 2016, 2020, 2050, 2060, 2068, 2070, 2090, 2100, 2110, 2122, 2130, 2150, 2164, 2170, 2180, 2185, 2188, 2201, 2220, 2232,
                                  2240, 2261, 2270, 2280, 2282, 2290,72000,72001,72003,72005,72007,72009,72011,72013,72015,72017,72019,72021,72023,72025,72027,72029,72031,72033,72035,72037,72039,72041,72043,72045,72047,72049,72051,72053,
                                  72054,72055,72057,72059,72061,72063,72065,72067,72069,72071,72073,72075,72077,72079,72081,72083,72085,72087,72089,72091,72093,72095,72097,72099,72101,72103,72105,72107,72109,72111,72113,72115,72117,72119,
                                  72121,72123,72125,72127,72129,72131,72133,72135,72137,72139,72141,72143,72145,72147,72149,72151,72153,74000,74050,74100,74150,74200,74250,74300,74350,74400,74450,78000,78010,78020,78030,78050,78100,
                                  78150,78218,78222,78224,78226,78350,78370]})
                              .type("geo_map")          // visualization type
                              .id("loc_id")            // key for which our data is unique on
                              .color({"value" : color_key})           // key for coloring countries
                              .labels({"value": false})
                              .format({ "text": function (text, key) {
                                  if (key == "State") {
                                      return text.toUpperCase()
                                  }
                                  else {
                                      return text
                                  }
                              }})
                              .text({"value": "State"})
                              .footer({"value": "Premium Rate Increase ($) (based on 2015 rate data)", "font": {"size": 14}})
                              .tooltip(jQuery.parseJSON(display_tx))         // keys to place in tooltip
                              .title(vistitle)
                              .draw()

**Comment by davelandry** [comment]
Is this happening with version 1.6.9? Can you try running your code with the development build in the main directory of this repo (1.6.10)? Running ```d3plus.version``` in the browser console will tell you which build you're on.

If it's still happening with the dev build, could you link me to the topojson file you're using so I can do some local troubleshooting? Thanks in advance.

**Comment by ltoole** [comment]
Ok... issue occurs with v1.6.10. It works fine with v1.6.8 and v1.6.9

**Comment by davelandry** [comment]
Please post a link to the topojson you are using so that I can troubleshoot the issue.

**Comment by ltoole** [comment]
Just installed v1.7.1 and the "zoomed out, small map" issue I outlined above is occurring. This is the raw topojson file I'm using... http://bl.ocks.org/mbostock/raw/4090846/us.json

**Comment by ltoole** [comment]
Yes that solved the problem. Interestingly, the absence of that number in
mute for version 1.6.9 did not seem to matter and the map size was rendered
appropriately.

Thank you for tracking this down.

By the way, I am using d3plus on this site... www.acaspotlight.org



*Lawrence Toole*
*Partner*

518 852-5373
www.magicloudLLC.com <http://www.magicloudllc.com/>
*lawrence.toole@magicloudLLC.com <lawrence.toole@magicloudLLC.com>*

**Comment by davelandry** [comment]
Cool stuff! Glad to see this worked out for you.
