### ISSUE TITLE
Unstacked area chart

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#284]

**Comment by csaladenes** [comment]
Change line d.d3plus[stacked + "0"] = flip - y0; to d.d3plus[stacked + "0"] = flip;

**Comment by davelandry** [comment]
thanks @csaladenes 

I've added a new "area" visualization type. "stacked" still works, but it's really now just a shorthand for saying `.y({"stacked": true})` on the "area" type.
