### ISSUE TITLE
Bug in "1.6.10 - Turquoise (Dev)"

### ISSUE THREAD

**Issue by zpz1982** [alexandersimoes/d3plus#294]
line 30307 of d3plus.js : 
    yValues = vars.x.ticks.visible;

should be
    yValues = vars.y.ticks.visible;

**Comment by davelandry** [comment]
:smirk: that messed me up yesterday too, it's fixed now!

**Comment by alexandersimoes** [comment]
@zpz1982 please feel empowered to contribute back w pull requests esp when you find small simple bugs like these.
