### ISSUE TITLE
Show quartile and whisker data in Box Plot tooltip

### ISSUE THREAD

**Issue by zpz1982** [alexandersimoes/d3plus#296]
Show top, 1q, 3q and bottom value in tooltip of box plot chart. No need list nested data.

**Comment by davelandry** [comment]
Good idea. We definitely should add the quartile/whisker data into the tooltip.

You can manually turn off the nested data list by toggling ["children" of .tooltip( )](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#tooltip):
```js
.tooltip({"children": false})
```

**Comment by venuduggireddy** [comment]
Tooltip is not showing up on iPad. However html tooltip example shows.

**Comment by davelandry** [comment]
IQR and Extent values will be visible in the tooltips of the next release. They can be toggled using 2 new keys inside of the .tooltip( ) method (they default to `true`):

```js
.tooltip({"extent": false, "iqr": false})
```

**Comment by davelandry** [comment]
@venuduggireddy, if your comment about the tooltip not showing up is a bug different from this issue, please create a new issue for it. This issue is solely for showing additional data in the tooltips for Box Plot visualizations.
