### ISSUE TITLE
d3plus.org is down

### ISSUE THREAD

**Issue by lukeadams** [alexandersimoes/d3plus#303]
I don't know who to contact, but d3plus.org isn't loading. All of the examples are broken, and the CDN is too (as far as I know).

**Comment by jspeis** [comment]
d3plus is hosted via Github so the outage may be related to the recent DDOS attacks https://status.github.com/messages?latest

**Comment by davelandry** [comment]
Got it figured out. The A Name for the domain was posting to one of GitHub's older servers. They now only reliably serve GitHub Pages from the 2 servers listed here: 
https://help.github.com/articles/my-custom-domain-isn-t-working/

**Comment by davelandry** [comment]
Also, thank you for reporting this @lukeadams. This is indeed the best place to contact us!
