### ISSUE TITLE
textwrap() is removing my text

### ISSUE THREAD

**Issue by gerritlo** [alexandersimoes/d3plus#307]
Dear all,

can somebody tell me why my text is dropped by textwrap()-method?
https://jsfiddle.net/bogbp7cu/

Thx

**Comment by davelandry** [comment]
Your x and y positioning was interfering with how textwrap determines the position and padding of the text. D3plus will automatically position your text inside of the shape directly above it in the DOM. 

Here is your updated fiddle with the x and y positions removed: https://jsfiddle.net/bogbp7cu/1/
