### ISSUE TITLE
Add options for interpolation & smoothing in line charts

### ISSUE THREAD

**Issue by amyzhaoyu** [alexandersimoes/d3plus#308]
It would be great if the d3plus line charts could include methods for line interpolation - see https://github.com/mbostock/d3/wiki/SVG-Shapes for the line interpolation modes that are available in d3.

**Comment by davelandry** [comment]
You can change the line interpolation method by accessing the "interpolate" property inside of .shape( ):
```js
.shape({"interpolate": "monotone"})
```
The list of available interpolation modes is in the wiki: https://github.com/alexandersimoes/d3plus/wiki/Visualizations#shape
