### ISSUE TITLE
Ability to specify the ticks shown on an axis

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#312]
https://groups.google.com/forum/#!topic/d3plus/hKH-9DD8zMA

**Comment by AlainRo** [comment]
.x() or .y()
{'ticks': {'number':5}} // default is 10

**Comment by davelandry** [comment]
In the next release, you'll be able to explicitly set the visible ticks on either axis. For example:

```js
.y({"ticks": [0, 5, 10, 50]})
```
