### ISSUE TITLE
Allow shapes to support custom image fills

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#317]
Mentioned in this Google Group: https://groups.google.com/forum/#!topic/d3plus/WiJcW-_ppZY

**Comment by miguelpaz** [comment]
This would be very good

Enviado desde mi iPhone

**Comment by jpmarindiaz** [comment]
+1

**Comment by descl** [comment]
+1
I would love to be able to add background in my treemap 
(mentioned on https://groups.google.com/forum/#!topic/d3plus/T4bfeScIMNE )

**Comment by lcoursey** [comment]
+1 billion

Would love custom images instead of colors on my charts.

**Comment by davelandry** [comment]
I've been hard at work on the 2.0 modularization of d3plus, and background images are supported in the new d3plus-shape module: https://github.com/d3plus/d3plus-shape

This feature will be available with the release of d3plus 2.0, and I suppose the new d3plus-shape module could be retrofitted into the 1.0 codebase when it's ready.

**Comment by descl** [comment]
Perfect! Thank you

**Comment by davelandry** [comment]
Closing this issue, as we're slowly moving development over to the 2.0 modules. Here is an example of how to do this: http://d3plus.org/examples/d3plus-hierarchy/background-image/
