### ISSUE TITLE
TextWrap Does not work correctly when using resize

### ISSUE THREAD

**Issue by ryanwark** [alexandersimoes/d3plus#325]
I've created a sample that shows the problem: http://jsfiddle.net/qbxmrf2m/2/

I think the problem is in the resize function, there're several calculations to determine if the text area and shape area, in this case a circle, have an appropriate ratio, then performs:

    if (maxWidth * (sizeMax / vars.size.value[1]) <= lineWidth) {
      if (sizeMax !== vars.size.value[1]) {
        vars.self.size([vars.size.value[0], sizeMax]);
      }
      flow(vars);
    } else {
      wrap(vars);
    }

It looks as though performing a `flow(vars)` all the time makes it work.

Thanks

**Comment by davelandry** [comment]
This is an issue with the default behavior of .size( ): https://github.com/alexandersimoes/d3plus/wiki/Text%20Wrapping#size

I've pushed a fix, which will be included in the next release. Until then, you can get around this by manually specifying a size range. I've updated your fiddle: http://jsfiddle.net/qbxmrf2m/3/
