### ISSUE TITLE
Children with same names but different parents being displayed

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#327]
https://groups.google.com/forum/#!topic/d3plus/jAmzlDnQTSM

It seems that when clicking into the squares of a tree map, it is not filtering the data appropriately by the parent nodes being isolated. Try clicking on C1 and then S: http://jsfiddle.net/chandrak_1972/xd5kp3q6/2/

**Comment by metasyn** [comment]
+1

**Comment by davelandry** [comment]
In addition to fixing the nesting problem, I also fixed an issue with incorrect values being shown in the tooltip.

This will be live in the next production release.

**Comment by metasyn** [comment]
@davelandry nice ! is there ETA on that by chance ?

**Comment by davelandry** [comment]
by the end of this week :+1:
