### ISSUE TITLE
Trigger events programatically

### ISSUE THREAD

**Issue by jazzido** [alexandersimoes/d3plus#328]
Hey,

I'm trying to link a couple visualizations through mouse events. Specifically, I want to trigger a hover event on a line chart. According to the docs, and what I could find in the code, there's no documented way to do it.

Is there any way to do it?

**Comment by davelandry** [comment]
We're making the roadmap for 2.0 right now, and we're thinking about how to have multiple visualizations talk to each other, here's the existing GitHub issue: https://github.com/alexandersimoes/d3plus/issues/110

As for triggering events in a single visualization, it looks like you've already found that issue: https://github.com/alexandersimoes/d3plus/issues/140 :wink:
