### ISSUE TITLE
Timeline has an error with small visualizations

### ISSUE THREAD

**Issue by TopologyApplied** [alexandersimoes/d3plus#333]
With the latest version 1.7.3, following this tutorial:
http://d3plus.org/blog/getting-started/2014/06/12/getting-started-1/

got following error:
Uncaught TypeError: Cannot read property 'map' of undefinedmodule.exports @ d3plus.js:27237module.exports.steps.push.function @ d3plus.js:21353module.exports.vars.self.selection.each.runFunction @ d3plus.js:33514module.exports.vars.self.selection.each.runStep @ d3plus.js:33557module.exports.vars.self.selection.each.nextStep @ d3plus.js:33497module.exports.vars.self.selection.each.runFunction @ d3plus.js:33518module.exports.vars.self.selection.each.runStep @ d3plus.js:33557module.exports.vars.self.selection.each.nextStep @ d3plus.js:33497module.exports.vars.self.selection.each.runFunction @ d3plus.js:33518(anonymous function) @ d3plus.js:33550

The version of d3plus tutorial above seems used 1.3.3, and there is no error.

**Comment by TopologyApplied** [comment]
The last working version is 1.6.9.

**Comment by davelandry** [comment]
Example: http://www.pij1415.pt/jangada_files/exportacoes-pt.html
Google Group Discussion: https://groups.google.com/forum/#!topic/d3plus/5fOgYYuZros

It seems that when the window goes under a certain width, the page errors out.
