### ISSUE TITLE
Every second cyrillic letter is capitalized

### ISSUE THREAD

**Issue by Vanuan** [alexandersimoes/d3plus#334]
Demonstration: http://jsfiddle.net/dwtqqn4v/1/

Notice that every second letter is capitalized. What's wrong?

**Comment by Vanuan** [comment]
The problem is somewhere here: https://github.com/alexandersimoes/d3plus/blob/master/src/string/title.coffee

**Comment by Vanuan** [comment]
How to disable this capitalization feature?

**Comment by Vanuan** [comment]
Got it:

    .format({text:function(text){return text;}})

**Comment by davelandry** [comment]
I was doing a check for all "non-letter characters", but it turns out that only applies to roman letters.

I kind of reversed my check and now it's detecting punctuation instead of characters.
