### ISSUE TITLE
Submit to jsDelivr CDN

### ISSUE THREAD

**Issue by passcod** [alexandersimoes/d3plus#345]
It would be nice to have this submitted to the jsDelivr CDN, as we could then use a single CDN'd request for it, e.g.

```
<script src="//cdn.jsdelivr.net/g/d3js@3,d3plus@1></script>
```

Maybe consider other "free" CDNs as well like https://cdnjs.com.

**Comment by davelandry** [comment]
We are already on CDNJS: https://cdnjs.com/libraries/d3plus :smirk: 

This jsDelivr CDN looks cool too, we'll look into it.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by davelandry** [comment]
seem to be working great!
`https://cdn.jsdelivr.net/npm/d3plus@latest/`
