### ISSUE TITLE
Questions about font, tooltip, and legend sizes

### ISSUE THREAD

**Issue by mcarrizosa4** [alexandersimoes/d3plus#348]
I can't seem to get the defult font-size to change on treemap. I tried using .labels({font{size: 20}}) and .font({"size":"10"}) and nothing changes the default size. I also need to make the tooltip larger than it is. Also when displaying 3 treemaps, the legend disappears. I think there is a max height in px and does not allow my legend to show up.

**Comment by davelandry** [comment]
Please post some code on [JSFiddle](https://jsfiddle.net) showing each of the problems you are having.

**Comment by mcarrizosa4** [comment]
There seems to be a hard coded minimum of 200px. When I displayed 3 treemaps by height if I don't specify 201+ px the legend, tooltip and percentages at the bottom disappear.

**Comment by mcarrizosa4** [comment]
![screen shot 2015-07-02 at 2 00 47 pm](https://cloud.githubusercontent.com/assets/13138668/8487748/d10ba4be-20c2-11e5-90b8-d47da66f5bac.png)
![screen shot 2015-07-02 at 11 27 47 am](https://cloud.githubusercontent.com/assets/13138668/8487752/d276fc68-20c2-11e5-9dac-d7551b677771.png)

**Comment by davelandry** [comment]
D3plus visualizations have a "small" mode which removes things like the legend at small sizes. You are correct that the current height cutoff is 200. These "small" cutoffs can be changed by passing new cutoffs to the [.width( )](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#width) and [.height( )](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#height) methods.

This is what you would need to say in order to change the minimum height to 300:
```js
.height({"small": 300})
```

Additionally, in order to specify a specific static size for the label font, you must also turn off the automatic resizing:
```js
.labels({"resize": false, "font": {"size": 10}})
```

**Comment by mcarrizosa4** [comment]
As for sublabels how can I put a term under the label title?



On Tue, Jul 7, 2015 at 8:55 AM, Dave Landry <notifications@github.com>
wrote:

> D3plus visualizations have a "small" mode which removes things like the
> legend at small sizes. You are correct that the current height cutoff is
> 200. These "small" cutoffs can be changed by passing new cutoffs to the .width(
> ) <https://github.com/alexandersimoes/d3plus/wiki/Visualizations#width>
> and .height( )
> <https://github.com/alexandersimoes/d3plus/wiki/Visualizations#height>
> methods.
>
> This is what you would need to say in order to change the minimum height
> to 300:
>
> .height({"small": 300})
>
> Additionally, in order to specify a specific static size for the label
> font, you must also turn off the automatic resizing:
>
> .labels({"resize": false, "font": {"size": 10}})
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexandersimoes/d3plus/issues/348#issuecomment-119247431>
> .
>



-- 
Michelle Carrizosa
Data Scientist

**Comment by davelandry** [comment]
Check out this Google Discussion: https://groups.google.com/forum/#!topic/d3plus/ly96_isqJSw

**Comment by mcarrizosa4** [comment]
Is there a maximum width also? I am trying to adjust the width to 90% of
the screen or at least bigger than what I currently have. Thank you

Michelle Carrizosa

On Tue, Jul 7, 2015 at 12:13 PM, Dave Landry <notifications@github.com>
wrote:

> Check out this Google Discussion:
> https://groups.google.com/forum/#!topic/d3plus/ly96_isqJSw
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexandersimoes/d3plus/issues/348#issuecomment-119307232>
> .
>



-- 
Michelle Carrizosa
Data Scientist

**Comment by davelandry** [comment]
Yes, you can set the same "small" property of width as you can with height (described in previous comment). Here is the full documentation for width: https://github.com/alexandersimoes/d3plus/wiki/Visualizations#width

**Comment by mcarrizosa4** [comment]
So I used the function for the labels which worked, but I have a treemap of
3 layers and it overwrote all of the titles for all of the treemaps. Do you
have any suggestions?[image: Inline image 1]

Michelle

On Thu, Jul 16, 2015 at 6:58 AM, Dave Landry <notifications@github.com>
wrote:

> Yes, you can set the same "small" property of width as you can with height
> (described in previous comment). Here is the full documentation for width:
> https://github.com/alexandersimoes/d3plus/wiki/Visualizations#width
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexandersimoes/d3plus/issues/348#issuecomment-121964745>
> .
>



-- 
Michelle Carrizosa
Data Scientist

**Comment by davelandry** [comment]
The image you tried to upload didn't work.

Can we move this discussion over to the Google Group?
https://groups.google.com/forum/#!forum/d3plus

GitHub issues are generally used for recording specific bugs and feature requests, and the Google Group is geared more towards conversations and learning/exploring.
