### ISSUE TITLE
Bar chart labels on top of squares

### ISSUE THREAD

**Issue by DerekTBrown** [alexandersimoes/d3plus#354]
I need to be able to put the "name" of each column in a bar chart above it, instead of in a tooltip.  How do I do this?

**Comment by davelandry** [comment]
Cool idea, currently not available.

**Comment by BuildingJarl** [comment]
+ 1

**Comment by davelandry** [comment]
Done. Will be available in the next release.

Labels will appear whenever a .text( ) key is set, and they adhere to all the same behaviors as labels in the other visualizations.
