### ISSUE TITLE
(nondeterministic) undefined error when using the UI option

### ISSUE THREAD

**Issue by m-ibm** [alexandersimoes/d3plus#356]
I defined a tree-map with this for the ui part:
```
.ui([
	{
		"method" : "text",
		"value" : [ { "Percent" : "per" }, { "Mutual Information" : "mi" } , { "Chi Squared" : "xi2" } ]
	}
])
```

This sometimes generates the following error:
```
Uncaught TypeError: Cannot read property 'data' of undefined
(anonymous function) 								@ d3plus.js:25267
(anonymous function) 								@ d3.min.js:3
H 													@ d3.min.js:1
ka.each 											@ d3.min.js:3
module.exports 										@ d3plus.js:25234
module.exports.steps.push.function 					@ d3plus.js:20324
module.exports.vars.self.selection.each.runFunction @ d3plus.js:32055
module.exports.vars.self.selection.each.runStep 	@ d3plus.js:32098
module.exports.vars.self.selection.each.nextStep 	@ d3plus.js:32038
module.exports.vars.self.selection.each.runFunction @ d3plus.js:32059
module.exports.vars.self.selection.each.runStep 	@ d3plus.js:32098
module.exports.vars.self.selection.each.nextStep 	@ d3plus.js:32038
module.exports.vars.self.selection.each.runFunction @ d3plus.js:32059
(anonymous function) 								@ d3plus.js:32091
```
Looking at the code in Chrome's debugger I see these properties of object d:
```javascript
d = Object {method: "text", value: Array[3]}
d.form		UNDEFINED!
```
![d3plus_bug 1](https://cloud.githubusercontent.com/assets/13468737/8852213/81eda062-315c-11e5-8ee2-149dc25e5609.png)

d.form should be initialized on line 25225 (just above the ui.each where the error happens)

As mentioned in the title, this is somewhat nondeterministic. On my Win7 machine I get it once every 5-10 times the treemap is drawn. On Linux this happens 4 out of 5 times.
The only solution I have for now is to keep refreshing (or remove the feature).

Is there a workaround or quick solution for this?

**Comment by davelandry** [comment]
I'm assuming that this is some DOM timing issue with the new elements sometimes not being fully entered before issuing the update event. I've just coded in a fix that should handle this edge case, and it will be part of the next release.
