### ISSUE TITLE
get id of clicked node

### ISSUE THREAD

**Issue by jmls** [alexandersimoes/d3plus#361]
using the ring type, is it possible to have data like

var sample_data = [
    {"name": "alpha", "size": 20, id: "1"},
    {"name": "beta", "size": 12, id: "2"},

and get the id of the node that was clicked instead of the label ?

what would the connections array look like ?

I have some data that may have duplicated labels ..

**Comment by davelandry** [comment]
You can pass a custom callback function to the .focus( ) method, which will get called anytime the focus changes (and the variable it receives is the new focus is). Here's a Google Group discussion about it: https://groups.google.com/forum/#!searchin/d3plus/.focus/d3plus/VHEMQWaQaos/kljNN0bYJmgJ
