### ISSUE TITLE
Text wrapping should support line breaks (ex. "\n")

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#362]
Would be useful when creating custom labels on Tree Map squares.

https://groups.google.com/forum/#!topic/d3plus/ly96_isqJSw

**Comment by mcarrizosa4** [comment]
I am trying to only get the tooltip to show up when I am on the last layer on the treemaps or when I hover. Is there a way to keep the tooltip not show up for on-click but on hover only? I tried the .timing() with mouseevents, transitions, ui but can't figure out what tooltip belongs to.

**Comment by davelandry** [comment]
Cool idea, I created a separate issue for it: #364
