### ISSUE TITLE
issue with legend on barchart?

### ISSUE THREAD

**Issue by markk-fmi** [alexandersimoes/d3plus#365]
First, thanks for d3plus!

I'm trying to add a legend to your barchart example and it does not appear in firefox or chrome.  Might you have a suggestion?  All I did was add the .legend line.

```
<!doctype html>
<meta charset="utf-8">

<script src="http://www.d3plus.org/js/d3.js"></script>
<script src="http://www.d3plus.org/js/d3plus.js"></script>

<div id="viz"></div>

<script>
  var data = [
    {"year": 1991, "name":"alpha", "value": 15},
    {"year": 1991, "name":"beta", "value": 10},
    {"year": 1991, "name":"gamma", "value": 5},
    {"year": 1991, "name":"delta", "value": 50},
    {"year": 1992, "name":"alpha", "value": 20},
    {"year": 1992, "name":"beta", "value": 10},
    {"year": 1992, "name":"gamma", "value": 10},
    {"year": 1992, "name":"delta", "value": 43},
    {"year": 1993, "name":"alpha", "value": 30},
    {"year": 1993, "name":"beta", "value": 40},
    {"year": 1993, "name":"gamma", "value": 20},
    {"year": 1993, "name":"delta", "value": 17},
    {"year": 1994, "name":"alpha", "value": 60},
    {"year": 1994, "name":"beta", "value": 60},
    {"year": 1994, "name":"gamma", "value": 25},
    {"year": 1994, "name":"delta", "value": 32}
  ]
  var visualization = d3plus.viz()
    .container("#viz")
    .data(data)
    .type("bar")
    .id("name")
    .x("year")
    .y("value")
    .legend({"value":true})
    .draw()
</script>
```

**Comment by davelandry** [comment]
Works fine for me in Firefox and Chrome. Can you post your code?

**Comment by markk-fmi** [comment]
Hi Dave.  Thanks for your reply.  I posted the code in the initial post right below my text.  I look forward to any insights you might provide.  mark.

**Comment by davelandry** [comment]
Ahh I see, I had to go in and edit your post (it wasn't showing up on GitHub).

Whenever you post code here, you have to escape it using three tildés for Markdown: https://help.github.com/articles/github-flavored-markdown/

I'll take a look now.

**Comment by davelandry** [comment]
I've found your problem. You're not setting a color variable. D3plus uses the ID as a default color scheme, but the legend won't appear until you explicitly set a color. Try adding this to your code:
```js
.color("name")
```
