### ISSUE TITLE
No tooltips for Line Plots in IE

### ISSUE THREAD

**Issue by agent96** [alexandersimoes/d3plus#368]
Hi - I've found the tooltip for the line plot is not working in Internet Explorer so it is not possible to know what each line represents on roll over.

I am using Edge but have tried emulating IE10 & 9.  Is it just me, or is this an issue for everyone.

I am looking at the example line plot here - and also replicated in my developments locally.
http://d3plus.org/examples/basic/9037371/

**Comment by davelandry** [comment]
I'll take a look into this. Probably related to the mouse event handling for lines.

**Comment by afenix** [comment]
Hello Dave!  Kudos to you and the awesome d3plus team for all your hard work.  I very much appreciate it.  I wanted to let you know that I'm also seeing this same issue for my Treemap graph, where all tooltips disappear when tested on IE11.  Any advice on where I can get started to try to resolve?

**Comment by davelandry** [comment]
Are you using a computer that also has a touch screen?

If so, we just found and fixed a bug that made tooltips not appear on computers with both mouse and touch controls.

**Comment by afenix** [comment]
Dave, I've only been using a computer with a mouse.  No touch screen.

**Comment by davelandry** [comment]
@afenix I believe this has been fixed as a result of other bugs. Would you mind trying you code using the development build of `d3plus.js` that is in the main directory of this repository?

**Comment by afenix** [comment]
Thanks for getting back to me on this Dave.  I just tested it and the tooltips are back (yes!) but the back button sinks to the bottom of the graph as can be seen by my screenshot.  I'm testing using browserstack, Windows 8 OS, and IE 10.
![treemap_back_button_shifted](https://cloud.githubusercontent.com/assets/3720992/13092629/ddf2c05c-d4b5-11e5-8147-e627f3970d52.jpg)

Any thoughts about that?

**Comment by davelandry** [comment]
@afenix good find! can you make a separate issue for the back button?
