### ISSUE TITLE
legend won't sort by id??

### ISSUE THREAD

**Issue by markk-fmi** [alexandersimoes/d3plus#369]
I am trying to alter the simple bar chart example to add a legend and sort it by id (i.e. the value of the name column in the data), but it seems to only sort by color.  I can change from ascending to descending sort, but never sort by id.  Might you offer a suggestion about my misunderstanding?  See code below:

'''
  var data = [
    {"year": 1991, "name":"alpha", "value": 15},
    {"year": 1991, "name":"beta", "value": 10},
    {"year": 1991, "name":"gamma", "value": 5},
    {"year": 1991, "name":"delta", "value": 50},
    {"year": 1992, "name":"alpha", "value": 20},
    {"year": 1992, "name":"beta", "value": 10},
    {"year": 1992, "name":"gamma", "value": 10},
    {"year": 1992, "name":"delta", "value": 43},
    {"year": 1993, "name":"alpha", "value": 30},
    {"year": 1993, "name":"beta", "value": 40},
    {"year": 1993, "name":"gamma", "value": 20},
    {"year": 1993, "name":"delta", "value": 17},
    {"year": 1994, "name":"alpha", "value": 60},
    {"year": 1994, "name":"beta", "value": 60},
    {"year": 1994, "name":"gamma", "value": 25},
    {"year": 1994, "name":"delta", "value": 32}
  ]
  var visualization = d3plus.viz()
    .container("#viz")
    .data(data)
    .type("bar")
    .id("name")
	.color("name")  /* reqd for legend */
    .x("year")
	.y({"stacked":true, "value":"value"})
	.legend({"order":{"sort":"desc", "value":"id"}})
    .draw()
'''

**Comment by davelandry** [comment]
Will be fixed in the next release :smile:
