### ISSUE TITLE
Add possibility to remove default rows(like "share" or "weight") in `tree map` tooltips

### ISSUE THREAD

**Issue by daigotsu** [alexandersimoes/d3plus#373]
Need to remove default "Share" and "Weight" position in tooltips. They are do not need by business logic, but no way to remove them by config.
example image http://imgur.com/alrbvAc

**Comment by davelandry** [comment]
You already can!

```js
.tooltip({"share": false, "size": false})
```

Here's all the keys available in the tooltip method: https://github.com/alexandersimoes/d3plus/wiki/Visualizations#tooltip
