### ISSUE TITLE
add custom class names to shapes

### ISSUE THREAD

**Issue by NikkiDreams** [alexandersimoes/d3plus#379]
I believe it would be ver beneficial to be able to pass a classname to the 
```<g class="d3plus_rect" />``` 
object to allow for greater style control. 
```<g class="d3plus_rect myClassName myOtherClassName ," />``` 
This would make it easier to control the visualizations without having to do all the logic or minute config objects in the viz functions  like this
```
   .foo({
        size: {
          min: 5
        },
        font: {
          size: 12,
          family: "Open Sans"
       },
        width: 5,
        color: "#ffffff",
      })
```
It is still very valuable to pass these fine control config objects, but the ability to simply do this

```
   .foo({
        classNames: 'fooClass barClass myBrandClass'
    })
```
where the custom classNames are appended to the d3plus className would make some visualzations setup much simpler, faster and allow for greater style control on the part of the developer. In my case I need that control because of the many variations of nodes depending on its state.

Food for thought. FYI I am really liking this library so far. It made my life a lot easier where I am pressed for time on a huge project. Thanks for your efforts.

**Comment by NikkiDreams** [comment]
Also forgot this option.
Pass classNames as a string or in a function that returns the string like:
```
 .foo(function(d){
        var myClassNames = data.nodeValues[d.ref] || d.className;
        if(myClassNames === undefined){
          return;
        }
        myClassNames = (typeof myClassNames === "string")? myClassNames : myClassNames.className;
        return myClassNames ? palette[myClassNames]: palette["gray-light"];
      })
```

**Comment by NikkiDreams** [comment]
HA! I think the perfect solution is this. It does not get more simple and elegant than this:
Line 265 & Line 267 of draw.js. Does not affect any of the d3plus functionality and allows me to use the values that already exist in my data. 

```   
   //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    // Groups Enter
    //--------------------------------------------------------------------------
    var opacity = vars.draw.timing ? 0 : 1
    var classNames = (vars.color.classNames)? " "+vars.color.classNames: ""
    var enter = selection.enter().append("g")
      .attr("class","d3plus_"+shape+classNames)
      .attr("opacity",opacity)
      .call(transform)
```

**Comment by NikkiDreams** [comment]
Here is the REAL fix I am using on the fork. Ignore my previous babbling and 8652a9b. I had a huge brainfart on that one.  This makes it so d3plus functionality remains unchanged and the user has the option of passing the className in the data itself. My data contains already has the className since the styles for each node are specific to user interactions and state.
```
//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    // Groups Enter
    //--------------------------------------------------------------------------
    var opacity = vars.draw.timing ? 0 : 1
    var enter = selection.enter().append("g")
      .attr("class", function(d){
        var classNames = (d.className)? " " + d.className: ""
        return "d3plus_" + shape + classNames
      })
      .attr("opacity",opacity)
      .call(transform)
```

**Comment by davelandry** [comment]
I love this idea, but we don't want to have any reserved words in a user's data (like "className").

The ideal solution would be to create a new ```.class( )``` method that accepts either a String key to use for the class name or a function that returns the class name.

I can help implement this if you're having trouble.

**Comment by NikkiDreams** [comment]
Cool. I'm not sure how to implement the .class() function but I will take a look at the other functions to figure it out. I agree with the className thing. I have been massively swamped on a very large project so  the brain is taking shortcuts just to get things done.
Thanks

**Comment by davelandry** [comment]
I totally get what you mean. I've been swamped as well.

That being said, I just implemented the new method :smirk:

**Comment by 5Movez** [comment]
YOU Rock! Thank You.
