### ISSUE TITLE
topojson object for .coords

### ISSUE THREAD

**Issue by ltoole** [alexandersimoes/d3plus#383]
I have a use case where I want to load a topojson file once from the server and then pass it to the .coords() method, perhaps multiple times given the user can select different visualization which use the same topojson file. Given it's the same underlying file, I want to load once and use multiple times, i.e. hold in memory as object.

I have the following jquery code:

us_json = (function () {
        var json = null;
        $.ajax({
            'async': false,
            'global': false,
            'url': "/maps/UStopo.json",
            'dataType': "json",
            'success': function (data) {
                json = data;
            }
        });
        return json;

The code above grabs the topojson file from my server and then assigns it to the us_topo variable. I then try and pass that variable to the d3plus .coords() method, like

.coords({"value": us_topo})

When I do so, I get following error...

Uncaught TypeError: Cannot use 'in' operator to search for 'type' in false      d3plus.full.min.js:18 

Does the .coords value have to be file location or can it be json object?

**Comment by davelandry** [comment]
It can absolutely be a json object. Can you upload your topojson file for us to take a look at?

**Comment by ltoole** [comment]
Attached is the json file...



*Lawrence Toole*
*Partner*

518 852-5373
www.magicloudLLC.com <http://www.magicloudllc.com/>
*lawrence.toole@magicloudLLC.com <lawrence.toole@magicloudLLC.com>*

**Comment by davelandry** [comment]
The attachment did not work. Did you attach it using the Github web interface?

It might be easier to post a link to the file.

**Comment by ltoole** [comment]
Here is a link for the json file...

https://www.acaspotlight.org/maps/UStopo.json

Thanks for taking a look at this issue.

**Comment by davelandry** [comment]
There's a syntax error in your topojson. When I try to load the file using ```d3.json```, I get the following error: 

```console
SyntaxError: Unexpected end of input(…)
```

**Comment by ltoole** [comment]
Yet that file loads into .coords method if I pass url for its location.

There's a syntax error in your topojson. When I try to load the file using
d3.json, I get the following error:

SyntaxError: Unexpected end of input(…)

—
Reply to this email directly or view it on GitHub
<https://github.com/alexandersimoes/d3plus/issues/383#issuecomment-156887596>
.

**Comment by davelandry** [comment]
Whoops, that's actually my bad. My copy of the file didn't download correctly.

I just pushed code to fix the issue. It had to do with explicitly setting the "value" key for .coords( ). In the meanwhile, you can just pass it to the method like this and it will work:

```js
d3.json("UStopo.json", function(error, data) {

    var visualization = d3plus.viz()
      .container("#viz")
      .type("geo_map")
      .coords(data)
      .draw();

  });
```

**Comment by ltoole** [comment]
Great. Thanks for looking at this.

**Comment by ltoole** [comment]
I tried your temporary work-around to no avail. My use case is the
following... I have the need to run multiple visualizations within the same
Web page and I want to load the topo json file once as a javascript object
and simply pass that to the .coords method to avoid retrieving the topo
json file multiple times from the server.  So as experiment I did this...

var us_json;

  $.getJSON("/maps/UStopo.json", function(json) {
      us_json = json;
   });

  d3.json(us_json, function(error, data) {

    var visualization = d3plus.viz()
      .container("#viz")
      .type("geo_map")
      .coords(data)
      .draw();

  });

And I get the following error...

GET http://localhost:5000/undefined 404 (NOT FOUND)

The d3plus documentation implied to me that I could pass a json object to
.coords, however it appears as if .coords is always expecting a URL and
always wants to retrieve a json file from provided path.



*Lawrence Toole*
*Partner*

518 852-5373
*lawrence.toole@magicloudLLC.com <lawrence.toole@magicloudLLC.com>*

**Comment by davelandry** [comment]
The d3.json function loads a file, just like the JQuery .getJSON function. You can ditch JQuery and your d3 code should look like this:

```js
d3.json("/maps/UStopo.json", function(error, data) {

    var visualization = d3plus.viz()
      .container("#viz")
      .type("geo_map")
      .coords(data)
      .draw();

});
```
