### ISSUE TITLE
Release textwrap as a standalone module

### ISSUE THREAD

**Issue by goodforenergy** [alexandersimoes/d3plus#384]
Hey there,

I have been searching for a text-wrapping utility to assist with wrapping text in my D3 project. Your text-wrapping functionality is perfect, but I don't need all of d3plus, just the text wrapping code.

I can (and have) forked the code, but I thought I'd ask if you'd consider providing text-wrapping as a standalone module that could be included via bower etc without the need for d3plus.

Thanks for the great utility!

Helen

**Comment by davelandry** [comment]
Thanks for the kind words! Glad to hear you're liking our text-wrapping.

We're currently in the planning stages for D3plus 2.0, which includes modularizing all of the codebase. This will include releasing the text-wrapping utility as a standalone package. Follow the new repo (which is just a skeleton for now) to see the progress: https://github.com/d3plus/d3plus-textbox

:beers:

**Comment by goodforenergy** [comment]
Excellent! Thanks! :)

**Comment by jazzido** [comment]
+10 — Same here. 

d3plus' `textwrap` is by far the best SVG text library out there. It'd be great to have it a as separate module.

**Comment by curran** [comment]
This might be a good module for trying out the new D3 4.0 plugin structure, described in [Let’s Make a (D3) Plugin](http://bost.ocks.org/mike/d3-plugin/). I could imagine this possibly being part of D3 itself one day.

**Comment by timelyportfolio** [comment]
:+1:

**Comment by davelandry** [comment]
We'll definitely be prioritizing this :-)

**Comment by jazzido** [comment]
I mercilessly butchered d3plus to make a `textwrap`-only package: https://github.com/jazzido/d3plus
Used for the treemap here: http://bahia.presupuestoabierto.org/dataset_ejecucion_gastos_bahia_user_bahia?chart=treemap&dimension=Jurisdicciones&measures=Aprobado

**Comment by davelandry** [comment]
@jazzido :+1: :beers:

**Comment by Hypercubed** [comment]
Just want to say that I am also looking forward to this... and am willing to help if I can.  I am currently using d3Plus (currently only the text wrapping) in a project using the SystemJS loader.  That means loading the `textwrap.coffee` source and transpiling (in browser) using the SystemJS coffee plugin.  It works but very slow during development.

**Comment by davelandry** [comment]
After a lot of coffee last week, it's done! And in most cases ~4 times faster!
https://github.com/d3plus/d3plus-text

Thanks to everyone for giving me the push to get this done. I'm looking for all the help I can get in testing it before considering it ready for a 1.0 release.

**Comment by goodforenergy** [comment]
Thanks so much @davelandry! Will pick it up today and give it a spin :)

**Comment by jazzido** [comment]
Thanks Dave! Will use it my current project :+1:
