### ISSUE TITLE
How to display the embed tree map

### ISSUE THREAD

**Issue by premkumar6030** [alexandersimoes/d3plus#386]
I had used iframe which you have given in eco. But the tree map is not display. How could I display the map. what are the steps the display the tree map.
I had used iframe alone inside HTML file to display it, but it dosn't display.

**Comment by metasyn** [comment]
This is a question better suited for the google group / forum.

https://groups.google.com/forum/#!forum/d3plus

Please submit your question there, along with a JSFiddle or bl.ocks.org of what you're working on.

**Comment by davelandry** [comment]
This is probably in response to this issue: https://github.com/alexandersimoes/oec/issues/104
