### ISSUE TITLE
'xmlns:xmlns:xlink': Uncaught NamespaceError

### ISSUE THREAD

**Issue by fpajer** [alexandersimoes/d3plus#389]
When using d3 >= 3.5.7 with the latest d3plus (1.8.0), I get the following error in my dev-env:

`Uncaught NamespaceError: Failed to execute 'setAttributeNS' on 'Element': The qualified name provided ('xmlns:xmlns:xlink') contains multiple colons.`

And any d3plus visualization does not initialize since the xlink namespace attribute doesn't get added to the svg, so I have to use d3 v3.5.6 for it to work.

This is probably due to this solved issue in d3:
https://github.com/mbostock/d3/issues/1935

**Comment by davelandry** [comment]
Great catch, I've just pushed this fix and it will be part of the next release.

**Comment by mariohmol** [comment]
samething here... worked perfect using d3 v3.5.6.. thanks a lot!

**Comment by isseu** [comment]
I have this problem if I use d3 v3.5.10 or higher
Works perfect with d3 v3.5.6 btw

**Comment by davelandry** [comment]
@isseu yes, d3 v3.5.7 fixed a bug that we were hard-coding a fix for. for now, you either need to continue using v3.5.6 until we release a new version of d3plus, or use the dev build that is in the main directory of this repository
