### ISSUE TITLE
GeoMap - Antarctica

### ISSUE THREAD

**Issue by itsmejainh** [alexandersimoes/d3plus#390]
Hi, 

Is there an option to exclude Antarctica from Map ?  Antarctica takes lot of space (vertically)

Just wondering if I can do something about it?

Thank you.

**Comment by heenamahour** [comment]
Hello,
Antarctica can be removed by excluding countries with id starting with "an"

Thanks

**Comment by alexandersimoes** [comment]
You can pass an object to the [.coords](https://github.com/alexandersimoes/d3plus/wiki/Data-Filtering#mute) method to mute (exclude) any geography like so: 

```js
.coords({"mute": "anata"}) // or whatever your ID for antarctica is
```

**Comment by itsmejainh** [comment]
Thanks heenamahour. That worked.
