### ISSUE TITLE
Wraptext padding

### ISSUE THREAD

**Issue by jugalpatel803** [alexandersimoes/d3plus#392]
Hi, I'm wondering if there is any way to apply some padding on the text that I've wrapped into my rect by using the container method. I haven't seen anything in the documentation. Thanks!

Code here: http://plnkr.co/edit/5UKhnYNEaMpbL6O1dNqQ?p=preview

**Comment by davelandry** [comment]
Yup, just pass an integer to the .padding( ) method:
https://github.com/alexandersimoes/d3plus/wiki/Text%20Wrapping#padding
