### ISSUE TITLE
Heatmap in .color()  : negative values

### ISSUE THREAD

**Issue by heenamahour** [alexandersimoes/d3plus#400]
It will be great if heatmap in .color() could accept negative values as well
Thanks

**Comment by mariohmol** [comment]
I use it with negative and works.. can u post a example?

**Comment by heenamahour** [comment]
@mariohmol  the documentation says the same https://github.com/alexandersimoes/d3plus/wiki/Visualizations#color


I tried in geomap by passing one of the value as negative, in that case it simply switches to default color

**Comment by mariohmol** [comment]
what about the heatmap option? 
this works for me.. where voto is a variable with negative values as well

```javascript

.color({
	    	  "range": [ "red" , "yellow" , "green" ],
	    	"value": "voto"
	    	})
```

**Comment by heenamahour** [comment]
Yes, looks good. But it must be an array of 3 colors ? I somehow, need to provide only two colors ..though it seems a viable option :+1:  

Thanks :)
