### ISSUE TITLE
color value showing in tooltip

### ISSUE THREAD

**Issue by ltoole** [alexandersimoes/d3plus#401]
I have situation with geo_map where I define the color for a heatmap like this...

.color({"value": "Max Monthly Premium Increase ($)", "heatmap": ["#ffdeb3","#fccd81","#fca43a","#fc7c12","#f75821","#c93602"], "missing" : "#FFFFCC"})

Then I define my tooltip like this...
.tooltip({"value": ["State","Risk of Losing Premium Tax Credits","Avg Monthly Premium Contribution Increase","Avg Percent Monthly Premium Contribution Increase","Additional Percent of Income for Health Insurance"]})  

When the tooltip is rendered, the "Max Monthly Premium Increase ($)" defined in .color is also shown in the tooltip. I don't want to see that key/value pair in the tooltip.

**Comment by davelandry** [comment]
I know the terminology is a bit confusing in the case of a Geo Map, but the ["size" key of the .tooltip( ) method](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#tooltip) refers to whether or not the current "sizing variable" (in this case, it references the color for Geo Maps) is put into the tooltip by default. You can turn it off like this:
```js
.tooltip({"size": false})
```
