### ISSUE TITLE
Horizontally centered text is shifted in Microsoft Edge

### ISSUE THREAD

**Issue by iamakulov** [alexandersimoes/d3plus#402]
In Edge, the [Tree Map example](http://d3plus.org/examples/basic/9029130/) looks as follows:

![Example](https://cloud.githubusercontent.com/assets/2953267/11844466/02f8f23e-a420-11e5-97d1-b796fc415d1b.png)

***

Currently, the text in Tree Map cells is aligned like this:

```html
<text text-anchor="middle">
    <tspan x="-50" dx="50">Text</tspan>
</text>
```

The `<tspan>`’s `x` and `dx` attributes have the same (but opposite) values, which does not shift the text in Chrome and Firefox. However, it appears that Edge interprets `text-anchor` and `dx` properties combination improperly. I can’t determine the actual behavior, but it looks like, with `text-anchor` being equal to `middle` or `end`, the `dx` units are twice smaller than they should be. Therefore, the `tspan` element in a Tree Map cell is shifted left.

A possible solution is to combine the `x` and `dx` properties so that only one of them (probably `x`) is used for alignment. If the solution is applied, the code will look as follows:

```html
<text text-anchor="middle">
    <tspan x="0" dx="0">Text</tspan>
</text>
```

and will not cause any issues in Edge (have checked this).

The `y`/`dy` attributes are not affected.

I can’t find any related bug report on connect.microsoft.com (and I haven’t reported it yet on my own).

The minimal reproducible case is [here](http://codepen.io/iamakulov/pen/mVVzMY). Compare the top right square in Chrome and Edge.

The issue affects Edge 12 and Edge 13.

**Comment by davelandry** [comment]
Thanks for this in-depth analysis, it should be fairly easy for me to fix this now!

**Comment by iamakulov** [comment]
@davelandry, any update on this?

If you’re busy at the moment, I could submit a PR if you help me find the approximate place where the `x`/`dx` attributes are calculated.

**Comment by davelandry** [comment]
@iamakulov I would love the help. here's where it gets set: https://github.com/alexandersimoes/d3plus/blob/master/src/textwrap/helpers/tspan.coffee#L15-L16

you should be able to see where and how those two variable are set, but it you have any questions let me know

**Comment by iamakulov** [comment]
Added #413 which fixes the issue.

A few comments:
* Readme mentions that gulp will run a local server, however, the server was disabled by 8ef5cd2. Made #414 to address this.
* With the latest sources, only the `d3plus.full.js` build is working. `d3plus.js` is broken: d3 [throws a NamespaceError](https://cloud.githubusercontent.com/assets/2953267/12698260/48943860-c7a9-11e5-827a-38ae0ff42bfd.PNG) when running the Tree Map example with it. This breaks the default development workflow as the `"dev"` gulp task cannot be used anymore. I haven’t found a quick way to fix this.
