### ISSUE TITLE
Dont show decimal points on bar chart

### ISSUE THREAD

**Issue by samundrak** [alexandersimoes/d3plus#404]
Is there anyway to not show decimal points on y axis just number skipped 5 each?i tried many way but unable to achieve it

**Comment by davelandry** [comment]
Can you post a [jsfiddle](https://jsfiddle.net) of your code? Not quite sure what you're referring to.

Custom number formatting may be what you're looking for: http://d3plus.org/examples/advanced/7760febcda3375b39e1f/
