### ISSUE TITLE
NoModificationAllowedError in IE and Edge

### ISSUE THREAD

**Issue by MarcelDe** [alexandersimoes/d3plus#407]
I get an error while drawing a ring visualization 
Works fine in Safari, Firefox and Chrome

IE : 11.0.10240.16603
EDGE: 20.10240.16384.0

Visual behaviour (see atachement):
Edges are drawn
Nodes not
Statustext saying "Drawing Visualization"

ERROR:
SCRIPT5022: NoModificationAllowedError
d3plus.js (24762,15)

![Uploading Schermafbeelding 2016-01-12 om 16.08.48.png…]()

CODE:
bounds.width += vars.labels.padding*scale[0]

CALLSTACK:
[Main Thread]
Anonymous function [Line: 24759, Col: 15], d3plus.js
Anonymous function [Line: 961, Col: 7], d3.js
d3_selection_each [Line: 967, Col: 30], d3.js
d3_selectionPrototype.each [Line: 960, Col: 5], d3.js
module.exports [Line: 24593, Col: 5], d3plus.js
module.exports [Line: 21794, Col: 7], d3plus.js
Anonymous function [Line: 33847, Col: 13], d3plus.js
runFunction [Line: 33846, Col: 11], d3plus.js
runStep [Line: 33894, Col: 13], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runFunction [Line: 33855, Col: 11], d3plus.js
runStep [Line: 33894, Col: 13], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runFunction [Line: 33855, Col: 11], d3plus.js
Anonymous function [Line: 33887, Col: 19], d3plus.js
[Async Call]
runStep [Line: 33886, Col: 17], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runFunction [Line: 33855, Col: 11], d3plus.js
runStep [Line: 33894, Col: 13], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runFunction [Line: 33855, Col: 11], d3plus.js
runStep [Line: 33894, Col: 13], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runFunction [Line: 33855, Col: 11], d3plus.js
runStep [Line: 33894, Col: 13], d3plus.js
[Async Call]
runStep [Line: 33886, Col: 17], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runStep [Line: 33906, Col: 13], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runFunction [Line: 33855, Col: 11], d3plus.js
runStep [Line: 33894, Col: 13], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runFunction [Line: 33855, Col: 11], d3plus.js
runStep [Line: 33894, Col: 13], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
[Async Call]
runStep [Line: 33886, Col: 17], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runFunction [Line: 33855, Col: 11], d3plus.js
runStep [Line: 33894, Col: 13], d3plus.js
nextStep [Line: 33834, Col: 11], d3plus.js
runFunction [Line: 33855, Col: 11], d3plus.js
Anonymous function [Line: 33887, Col: 19], d3plus.js
[Async Call]
runStep [Line: 33886, Col: 17], d3plus.js
Anonymous function [Line: 33912, Col: 7], d3plus.js
Anonymous function [Line: 961, Col: 7], d3.js
d3_selection_each [Line: 967, Col: 30], d3.js
d3_selectionPrototype.each [Line: 960, Col: 5], d3.js
vars.self [Line: 33813, Col: 5], d3plus.js
d3_selectionPrototype.call [Line: 974, Col: 5], d3.js
module.exports.process [Line: 28785, Col: 7], d3plus.js
module.exports [Line: 14235, Col: 5], d3plus.js
module.exports [Line: 14450, Col: 7], d3plus.js
[Async Call]
self.defer [Line: 1, Col: 1], angular.js
timeout [Line: 1, Col: 1], angular.js
Anonymous function [Line: 1, Col: 1], angular-ui-router.js
jQuery.event.dispatch [Line: 1, Col: 1], jquery.js
elemData.handle [Line: 1, Col: 1], jquery.js
[Async Call]
jQuery.event.add [Line: 1, Col: 1], jquery.js
Anonymous function [Line: 1, Col: 1], jquery.js
each [Line: 1, Col: 1], jquery.js
jQuery.prototype.each [Line: 1, Col: 1], jquery.js
on [Line: 1, Col: 1], jquery.js
bind [Line: 1, Col: 1], jquery.js
link [Line: 1, Col: 1], angular-ui-router.js
invokeLinkFn [Line: 1, Col: 1], angular.js
nodeLinkFn [Line: 1, Col: 1], angular.js
compositeLinkFn [Line: 1, Col: 1], angular.js

**Comment by MarcelDe** [comment]
![schermafbeelding 2016-01-12 om 16 08 48](https://cloud.githubusercontent.com/assets/1199759/12267343/f2bab3d4-b947-11e5-86ee-1176ca1f6215.png)

**Comment by MarcelDe** [comment]
I've tested also with the demo http://d3plus.org/examples/basic/9034389/
Same result!  

So maybe the demo is a nice starting point to address the problem
![capture](https://cloud.githubusercontent.com/assets/1199759/12583238/93c87134-c439-11e5-986c-7a8ca76f018b.PNG)

**Comment by davelandry** [comment]
Thanks for finding this one, just pushed the fix and it will be part of the next release!
