### ISSUE TITLE
nested aggs()

### ISSUE THREAD

**Issue by csaladenes** [alexandersimoes/d3plus#409]
We have a nested visualization with 3 levels.
When setting the the data aggregation, we would like the first level to be a sum of the second level, which in turn should be an average of the third - i.e. hierarchrical aggregation by level. Is this possible? I was thinking something like .aggs({"value": "{"level 1":"sum","level 2":"mean"}"})

**Comment by davelandry** [comment]
whoa, never thought about that. would be a little difficult to implement, but here's something that might help in the meantime:

all of the methods in d3plus support being passed a [callback function](https://github.com/alexandersimoes/d3plus/wiki/Methods#callback) as a second variable, which gets called anytime that method is changed. you could theoretically pass the .depth( ) method a callback function, and inside that function you could change the aggregation method as the depth changes. something like this:
```js
viz.depth(0, function(d) {
  viz.aggs({"value": d === 0 ? "sum" : "mean"});
});
```

**Comment by davelandry** [comment]
@csaladenes, another work around I just remembered that might work better for you: [.aggs( )](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#aggs) also supports functions!

```js
.aggs({"value": function(leaves){
  return d3.sum(leaves, function(d) { return d.value; });
}});
```
