### ISSUE TITLE
Cannot read property 'sourceEvent' of null, mouseover events in a treemap

### ISSUE THREAD

**Issue by cima007** [alexandersimoes/d3plus#410]
Hi
Im ussing laravel 4.2 as a php framework and d3plus for making a treemap out of some data from a Mysql database.
The issue is when i move the mouse over the graph, the tooltip does not display and the console receives the message of Cannot read property 'sourceEvent' of null at d3.js:line 528
When the mouse leaves a box i receive a second error message "Cannot read property 'toElement' of null"
:(

**Comment by davelandry** [comment]
can you post some sample code replicating this error in a live environment? are you seeing this in one specific browser?

**Comment by cima007** [comment]
I re-do everything 
Before i was passing the variable of the query with compact (php) to the HTML where i was testing the javascript
Now i Json_encode the variable pass it trough with /PHP-Vars-To-Js-Transformer, and Jsonparse the variable. 

The big change was the CDN, from this ones:
<script src="http://www.d3plus.org/js/d3.js"></script>
<script src="http://www.d3plus.org/js/d3plus.js"></script>
to this ones:
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.13/d3.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3plus/1.8.0/d3plus.full.min.js"></script>
For some reason the CDN was giving "Failed to execute 'setAttributeNS' on 'Element'" error 

Everything works now :)

**Comment by davelandry** [comment]
Glad you got it working!

The d3plus.full.min.js library that you are loading includes d3, so you can get rid of loading d3 separately!
