### ISSUE TITLE
d3plus text wrap in svg path

### ISSUE THREAD

**Issue by satya23k** [alexandersimoes/d3plus#411]
the wrap function works great inside rectangle and a circle, but not working when I am using an svg path(lets say when creating a pie chart), wanted to know if there is any work around.

thanks.

**Comment by davelandry** [comment]
The text wrapping only supports rectangle and circles. Determining the space available in an n-side polygon isn't trivial, so we won't be supporting it in this repo. If you're still interested in this feature, please create an issue in the newly released module's repository: https://github.com/d3plus/d3plus-text

**Comment by satya23k** [comment]
thanks. I will check it out
