### ISSUE TITLE
Shorter Words are not centered in nodes

### ISSUE THREAD

**Issue by CodeQueen5M** [alexandersimoes/d3plus#412]
<img width="410" alt="screen shot 2016-01-24 at 5 15 43 pm" src="https://cloud.githubusercontent.com/assets/15677731/12540444/454c4aa2-c2be-11e5-8e83-62fbdf4c1e6f.png">

I just merged your latest release into my fork and noticed that shorter words are not being middle aligned as they were before.

**Comment by davelandry** [comment]
That's really strange. Can you some sample data so I can use your strings? Also, how are you setting the font-family?

**Comment by CodeQueen5M** [comment]
I am setting the font like this.
```
d3plus.viz()
      .font("Open Sans Condensed")
```
Other than that I have a css definition.
```
 svg text {
    font-family: "Open Sans";
    font-weight: 800;
}
```

Here is a simplified Data set: In this set none of the text nodes are middle aligned.
```
[
  {
    "type": "ecocategory",
    "ref": "root",
    "name": "Acme Co.",
    "color": "brown"
  },
  {
    "type": "ecocategory",
    "ref": "category_3",
    "name": "Other",
    "color": "blue",
    "ecoSubCategory": [
      {
        "type": "ecosubcategory",
        "ref": "category_3_subcategory_1",
        "name": "child node 1",
        "color": "blue-light"
      },
      {
        "type": "ecosubcategory",
        "ref": "category_3_subcategory_2",
        "name": "child node 2",
        "color": "blue-light"
      },
      {
        "type": "ecosubcategory",
        "ref": "category_3_subcategory_3",
        "name": "child node 3",
        "color": "blue-light"
      }
    ],
    "hasChildren": true
  }
]
```

Generated SVG from node with uncentered text:
```
<g class="d3plus_rect gray" opacity="1" style="cursor: pointer;" transform=
    "translate(650,225),scale(1,1)">
        <rect class="d3plus_data" fill="#A2A4AB" height="90" opacity="1" rx=
        "46" ry="46" shape-rendering="auto" style="stroke: rgb(130, 132, 138);"
        transform vector-effect="non-scaling-stroke" width="90" x="-45" y=
        "-45"></rect>
        <text class="d3plus_label" fill="#565758" font-family="sans-serif"
        font-size="427px" font-weight="200" id="d3plus_label_category_3_rect"
        opacity="1" pointer-events="none" style="font-size: 427px;"
        text-anchor="middle" transform=
        "rotate(0,0,0)scale(0.0532670528243478)translate(0,0)rotate(0, 0, 0)translate(0,271.15988311707343)"
        x="-834.7998831170735" y="-834.7998831170735">
            <tspan dominant-baseline="alphabetic" dx="834.7998831170735px" dy=
            "469.70000000000005px" style="baseline-shift: 0%;" x=
            "-834.7998831170735px"></tspan>
            <tspan dominant-baseline="alphabetic" dx="834.7998831170735px" dy=
            "469.70000000000005px" style="baseline-shift: 0%;" x=
            "-834.7998831170735px">
                Other
            </tspan>
        </text>
    </g>
```

**Comment by goodforenergy** [comment]
FYI I'm seeing this too. Font styles are inherited from the body. Generated SVG of the uncentered node:

```
<g transform="translate(2.0630937268983054e-14,-336.92877462052104)">
	<circle r="37.26741194812636"></circle>
	<text class="ng-label text-wrap" text-anchor="middle" font-size="14px" x="-37.26741194812636" y="-37.26741194812636" style="font-size: 14px;" transform="rotate(0, 0, 0)translate(0,18.787411948126355)"><tspan x="0px" dy="15.400000000000002px" dominant-baseline="alphabetic" style="baseline-shift: 0%;"></tspan><tspan x="0px" dy="15.400000000000002px" dominant-baseline="alphabetic" style="baseline-shift: 0%;">Discharges</tspan></text>
</g>
```

<img width="320" alt="screen shot 2016-02-05 at 4 56 10 pm" src="https://cloud.githubusercontent.com/assets/1276346/12837679/bb0a7790-cc29-11e5-9374-8ab5549e2da5.png">

**Comment by davelandry** [comment]
hmm, in both examples it looks like there's an empty `<tspan>` element that's created before the actual used one. thanks everybody for giving such detailed reporting.

only other thing I can think to ask is: what browser is everybody using?

**Comment by NikkiDreams** [comment]
I use Chrome and Firefox. My users have reported it on IE and Safari on Mac and Windows.

**Comment by goodforenergy** [comment]
I'm seeing it on Chrome and Safari on Mac and IE9 and 10 on my VMs. Haven't tested on newer IEs.

**Comment by goodforenergy** [comment]
Seeing it on IE11 too.

**Comment by goodforenergy** [comment]
Oh - I tried to cherry pick the fix for [labels in Edge](https://github.com/DataUSA/datausa-site/issues/203) onto my working branch, and I saw this bug. I think [this](https://github.com/alexandersimoes/d3plus/commit/8fada2007ef44485a102db4fc6d0645b90830647) is the offending commit.

**Comment by davelandry** [comment]
wait, is everyone seeing this in the public build or in the current dev build in the repo?

**Comment by goodforenergy** [comment]
I'm using a dev build :)

**Comment by davelandry** [comment]
Fixed this! You guys can grab the dev build of `d3plus.js` from the main directory until I get the full release out the door.

Thanks again for all the help.

**Comment by goodforenergy** [comment]
Thanks so much Dave! You're a star.
