### ISSUE TITLE
Small UI issues

### ISSUE THREAD

**Issue by m-ibm** [alexandersimoes/d3plus#421]
I updated to the latest version, 1.9.0, and encountered a number of small, yet annoying, UI issues.

![d3plus_ui_issue](https://cloud.githubusercontent.com/assets/13468737/13033858/dfbc907c-d32d-11e5-8794-738e698e2589.png)

- Breaking numbers across rows looks bad

- Displaying a single digit from a number looks even worse (should have a minimum displayed chars after which font is reduced or text is removed)

- You have same size rectangles for which some display text and others do not (even with same text)

- Is the 'special' group rectangle which held 'the rest' of the smaller items still available/configurable?
The current situation makes the tree-map unusable with larger number of rectangles (they get too small to read the text, or even properly click them)

- Is there a way to configure the "Drawing visualization" text to not be displayed for certain actions?
I have a custom element that toggles the tree-map text. It looks much cooler before when it  just flicked and the new text appeared than having 10-15% of the map covered with the message for 1-2 seconds.

**Comment by davelandry** [comment]
Would you mind splitting this list out into separate issues?

The special group can be turned on using the "threshold" variable of .size( ): https://github.com/alexandersimoes/d3plus/wiki/Visualizations#size

The "Drawing visualization" text can be modified using the .messages( ) method: https://github.com/alexandersimoes/d3plus/wiki/Visualizations#messages

**Comment by m-ibm** [comment]
Done.
