### ISSUE TITLE
Y Axis label error on box plot

### ISSUE THREAD

**Issue by dgriffs** [alexandersimoes/d3plus#426]
The feature whereby vertical and horizontal lines animate from a data point to show their exact position on the x and y axes is happening on Box Plots, erroneously I think. See [http://jsfiddle.net/dgriffs/5dSpz/14/]

From my analysis, it happens when the Median coincides with an actual data value. On the example attached, you can see that it also fires the line for the value 20 (second box from the left) on to the y axis at the 25 mark.

Should this feature be disabled for box plots anyway?

Many thanks

**Comment by davelandry** [comment]
eww gross. yeah my vote is to remove it.
