### ISSUE TITLE
textwrap with text containing "." expands to ".."

### ISSUE THREAD

**Issue by rmatejka** [alexandersimoes/d3plus#427]
I'm using d3Plus to wrap IP addresses and it works great except for this odd edge case. When passed "10.199.2.4", it is rendered as "10.199..2.4". Same occurs for "10.199.0.3". This is the call I'm using:

d3plus.textwrap()
                    .container(nodeText)
                    .x(-69)
                    .width(138)
                    .resize(false)
                    .padding(0)
                    .text("10.199.2.4")
                    .draw();

OUTPUT:
`<text xmlns="http://www.w3.org/2000/svg" class="nodeName resolution-big bg-success" font-size="11px" style="font-size: 11px;" text-anchor="middle" transform="rotate(0) translate(0 -2.42)" x="-69" y="35"><tspan style="baseline-shift: 0%;" dominant-baseline="alphabetic" x="0px" dy="12.1px">10.199..2.4</tspan></text>
`

**Comment by davelandry** [comment]
Great catch, thanks!

**Comment by rmatejka** [comment]
I just had a chance to pull latest and revert my code to set the split array manually - but the original problem is back - not splitting on period. Am I not making the call correct?

d3plus.textwrap()
                    .container(nodeText)
                    .x(leftSideOffset)
                    .width(textLabelWidth)
                    .resize(false)
                    .padding(0)
                    .text({ value: label, split: ["-", "/", ";", ":", "&", "."] }) /// Added "." 
                    .draw();

**Comment by davelandry** [comment]
@rmatejka whoops, sorry about that. Don't know what happened, but it's fixed now. Will be a part of the next release.

**Comment by rmatejka** [comment]
Chuckle - been there - way too any times! Thanks.
