### ISSUE TITLE
Treemap back button moves to lower left corner in IE10

### ISSUE THREAD

**Issue by afenix** [alexandersimoes/d3plus#428]
#When testing a treemap chart in IE browsers (specifically IE10) the back button sinks to the lower left corner of the chart (instead of at the top left corner).  My testing environment was Browserstack, Windows 8 OS, and IE 10.
![treemap_back_button_shifted](https://cloud.githubusercontent.com/assets/3720992/13153529/80d2832e-d629-11e5-906b-98fd661241da.jpg)

**Comment by davelandry** [comment]
Good find! This also helped me fix an issue with edge label background colors in rings.

**Comment by afenix** [comment]
That's great to hear Dave!

**Comment by drvillamizar** [comment]
Hello! The same thing happens to me in google chrome :(
![d3plus1 0_bug_treemap](https://user-images.githubusercontent.com/23440680/81363196-5c8ef680-90a8-11ea-8cf8-52aeae0d2422.png)
