### ISSUE TITLE
Scatter Plot - Legend

### ISSUE THREAD

**Issue by itsmejainh** [alexandersimoes/d3plus#430]
Hi, 

I am trying to plot simple Scatter Plot using D3Plus. Here is the fiddle - http://jsfiddle.net/Bq7Lc/9/

In this, I have used size function also to control size of circles and in doing so, I do not get labels for all circles in one go. 

Also, legends do not appear. I tried enabling legend but still it doesn't work. Can someone please look?

Thanks,
Himanshu.

**Comment by davelandry** [comment]
Labels will not be placed inside circles that are too small for text.

To enable the legend, you must explicitly set a .color( ) variable. I've updated your fiddle: http://jsfiddle.net/Bq7Lc/10/
