### ISSUE TITLE
SVGElement.offsetHeight deprecation

### ISSUE THREAD

**Issue by satya23k** [alexandersimoes/d3plus#431]
Hi,
Just wanted t to remind you guys that SVGElement.offsetHeight is being deprecated and will be removed by April 2016.

warning in chrome console:
'SVGElement.offsetHeight' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.

**Comment by iamakulov** [comment]
Here’s the console warning:

![chrome_2016-02-24_15-07-40](https://cloud.githubusercontent.com/assets/2953267/13284894/61640b3c-db08-11e5-8ca2-bbaa2b2e002b.png)

And the exact place in the minified code:

![chrome_2016-02-24_15-09-03](https://cloud.githubusercontent.com/assets/2953267/13284920/8d6cb56c-db08-11e5-8659-b9c1ff30d71c.png)

**Comment by iamakulov** [comment]
Looks like [this is the corresponding place](https://github.com/alexandersimoes/d3plus/blob/master/src/font/sizes.coffee#L31). (I’m using the outdated library version, so the minified code on a previous screenshot is a bit different.)

[ChromeStatus](https://www.chromestatus.com/features/5724912467574784) states that `offsetHeight` for SVG is only implemented in Blink/Webkit and is not supported by any other browser, so I believe we can easily delete this. @davelandry, should I submit a PR?

**Comment by davelandry** [comment]
Great find @iamakulov. I'm a little scared of this breaking stuff, but there's only 1 way to find out. Please do a pull request!
