### ISSUE TITLE
D3plus with Karma throws an error

### ISSUE THREAD

**Issue by chrilehner90** [alexandersimoes/d3plus#439]
Hey,

we are using D3plus in our project for visualizations.
Our tests are executed by PhantomJS with Karma.

We have to include all our plugins in our karma.conf file.

When we execute our tests then we get the following error:

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating 'compile.bind(undefined, proc)')
  at /Users/chri/Documents/FHS_workspace/Master/Masterprojekt/web-app/bower_components/d3plus/d3plus.js:8728
```
Therefore none of our tests is executing.

It seems like this file cannot be found (d3plus.js in line 8671):
```
var compile = require("./compile.js")
```

Any ideas how to fix this?
Thanks in advance!

**Comment by chrilehner90** [comment]
This one is resolved. It was an error in the karma.conf file.

Thanks anyways!

**Comment by davelandry** [comment]
:+1:

would you mind sharing what you did to fix it?

**Comment by dcballs** [comment]
sharing your fix would be nice 👍
