### ISSUE TITLE
Textwrap: "dot" breaks the word (example currency)

### ISSUE THREAD

**Issue by Joe312341** [alexandersimoes/d3plus#442]
Hello,

Since I updated to 1.9.1 the textwrap functionality breaks on "dot" 

Example: decimals get broken up

See fiddle: http://jsfiddle.net/zrzx5Lvu/30/

Have the issue in all tested browsers (IE, Edge, Chrome, FF)

Is this a bug?
Thanks, Joe

**Comment by rmatejka** [comment]
Unfortunately that was a feature addition - breaking on a period was set as a default. See https://github.com/alexandersimoes/d3plus/issues/416. Maybe Dave will pull period from the defaults. In the short term, you can set back the old options if needed:

.text( { split:["-", "/", ";", ":", "&"], value:yourText } )

Hope this helps,
Rick

**Comment by Joe312341** [comment]
So this was only done due to the long ip use case?

I would argue that decimal point numbers and thousand separators (dot in some countries) would occur more often?

Anyways thank you for pointing out a quick fix, hope to get some discussion on this.
Thanks,
Joe

**Comment by rmatejka** [comment]
If ipAddress display was the primary motivation (I believe it was), I agree that decimals in number would occur more often and would generally not want those to split by default.

Rick

**Comment by Joe312341** [comment]
What is your opinion on this @davelandry ? Is a revert to be expected or should I just go with the quick fix?

**Comment by davelandry** [comment]
guys, couldn't agree more. this caused way more problems I didn't predict. this will be reverted back with the next release.
