### ISSUE TITLE
Breaking numbers across rows

### ISSUE THREAD

**Issue by m-ibm** [alexandersimoes/d3plus#444]
Split issue: [https://github.com/alexandersimoes/d3plus/issues/421#issuecomment-184007551]()

Breaking numbers across rows is visually bad )not that breaking at the percent sign would look much better here).
I suggest preferring to shrink that font for text shorter than X characters.
I would also check that the dot you break at is not part of a float (I am sure other cases will appear, but is probably the worst of them).

![d3plus_ui_issue](https://cloud.githubusercontent.com/assets/13468737/13555621/239c5312-e3ce-11e5-9627-74fa815290b2.png)

**Comment by davelandry** [comment]
I believe this has been fixed as a result of #442. Can you confirm by testing with the latest development build of `d3plus.js` that has been pushed to this repo?

**Comment by m-ibm** [comment]
Yes, this seems to be solved, at least for our use case.
