### ISSUE TITLE
Display a minimum of X chars

### ISSUE THREAD

**Issue by m-ibm** [alexandersimoes/d3plus#445]
Split issue: [https://github.com/alexandersimoes/d3plus/issues/421#issuecomment-184007551]()

Displaying a single digit (or char) looks bad.
There should be a minimum of displayed chars after which font is reduced or text is removed. Not sure what that minimum might be, but I would say 3 (could have it configurable).

![d3plus_ui_issue](https://cloud.githubusercontent.com/assets/13468737/13555635/caf64424-e3ce-11e5-8f96-9d2001f9a420.png)

**Comment by davelandry** [comment]
I believe this is also related to #444. Please confirm.

**Comment by m-ibm** [comment]
This also looks to be fixed in the latest release.
