### ISSUE TITLE
override specific level's mouse events

### ISSUE THREAD

**Issue by heenamahour** [alexandersimoes/d3plus#447]
Hi,

In grouped treemap, I need a click action at the deepest level. but somehow if I use mouse(), it overrides the existing click handling at parent level ( i.e, clicking on parent should give child which is by default happening in d3plus) and when the deepest level is encountered then, instead of redirecting back to the parent level, I need to have a custom click handling.

Please let me know how I can work on that.

Thanks !

**Comment by heenamahour** [comment]
@davelandry  Please let me know how to ensure the default click event handling of treemap is not over ridden as I specify a custom click event using mouse() and how this could be done at only the child level.

Thanks !!

**Comment by davelandry** [comment]
Currently it's all or nothing. You can recreate the default behavior by changing the .depth( ) and the "solo" of .id( ) when clicking on a parent node. Here is the internal default behavior: https://github.com/alexandersimoes/d3plus/blob/master/src/viz/helpers/shapes/draw.js#L713-L763

**Comment by itsmejainh** [comment]
Hi Dave !

Any update on mouse() event handling at deepest child to override default event of going back to parent level.

thanks.

**Comment by heenamahour** [comment]
Thanks @davelandry  !! That helped me for now. :+1:

**Comment by heenamahour** [comment]
@davelandry  any updates if it will be available by next release ? :-) 

Waiting for it ! Right now, I have hardcoded the functionality I needed in my local copy of d3plus itself, which I somehow feel is not the right approach. 

On a unrelated note, I must say this library is too great to use over d3.js :+1:  hats off Dave ^_^ ! It will be great if we have a mailing list for d3plus as well to expand d3plus's community !

**Comment by nickewa** [comment]
I'll throw my hat in the bucket here as well, it'd be amazing to have this functionality available as it's something that I'm also currently needing.

**Comment by davelandry** [comment]
I think I've found a quick and elegant solution (thanks to #534): I'm going to add in the ability that if you return `true` from a custom mouse function, it will run the default behavior in addition to any behavior you have specified (if any).

Working on it right now.

**Comment by tloy1966** [comment]
Hi,

Just ask, it that mean you can do some thing then just return true in click event?

**Comment by heenamahour** [comment]
@tloy1966  Yeah, looks like as per #534 :+1: Thanks to @davelandry :)
