### ISSUE TITLE
Bubble graph - colors and layout options?

### ISSUE THREAD

**Issue by emergingdzns** [alexandersimoes/d3plus#448]
I'm really excited to use the D3Plus library. However, I have two questions before I dig in and spend a lot of time. I apologize if this isn't the correct forum for questions.

1. With the old D3 library, when we created a bubble graph, the bubbles would automatically color in a range of colors based on their size. It was using the D3 scale category20c function. Is this (or something similar) available in the D3Plus library on bubble graphs?

2. In the example for the bubble graphs, it shows all the bubbles fitting into a circular area. Is it possible to define that container as a rectangular space? It would be nice to fill an area on the site and not have a lot of whitespace in the corners.

Thanks for the help!

**Comment by davelandry** [comment]
Take a look at the ["scale" property of .color( )](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#color). You would set it like this:
```js
.color({"scale": "category20c"})
```

Rectangular containers are not currently supported. D3plus uses the [D3 Pack Layout](https://github.com/mbostock/d3/wiki/Pack-Layout), which puts them in a circle. My understanding is that rectangles could work by using a force layout/quadtree to pack them in the inner bounds. If you're interested in this feature, please create a separate issue about it to start the discussion.

I have no problem using Github for discussions/questions. There's also a [Google Group](https://groups.google.com/forum/#!forum/d3plus) that is geared more towards discussion/implementation.

Happy coding :beers:
