### ISSUE TITLE
Bar Chart change tooltip header 

### ISSUE THREAD

**Issue by Joe312341** [alexandersimoes/d3plus#449]
Hello,

Once I set .text() to display values inside the bars, the legend and tooltip title automatically take that .text() value. Which is not what I want. Am I overlooking something?

Fiddle: http://jsfiddle.net/Bq7Lc/12/

I was able to set the text for legend by using the text function but not sure how to access the tooltip title.

To be clear I would like the tooltip to display the name value as its title instead of the text value.

Thanks, Joe

**Comment by davelandry** [comment]
Take a look at the ["text" property of .labels( )](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#labels). The .text( ) accessor will always be used for tooltip titles, but you can manually override where .labels( ) gets it's value (like how you were previously doing it for the legend): http://jsfiddle.net/Bq7Lc/13/
