### ISSUE TITLE
issue with box-plot graph

### ISSUE THREAD

**Issue by chemaveba** [alexandersimoes/d3plus#454]
Hello,

I´m trying to make a box plot with n compounds, but the X axis are compound (e.g compounds 1, 2..) and not year. Is it possible to make a box plot without dates?

Thanks

Best Regards

**Comment by davelandry** [comment]
Yes, that should work. Can you post your code to something like jsfiddle or codebin so we can help?

**Comment by chemaveba** [comment]
Hello Dave,

Here is my code. It works but I need change $fecha 1 and $fecha 3 for
$titulo1 and $titulo2. 

Best Regards
  <?php
  $temp1=array(80,85,88,89,90,93,95,96);
  $temp3=array(75,77,78,79,80,81,82,83);
  $titulo1='PCB81';
  $titulo2='PCB18';
  $fecha1=03;
  $fecha2=04;
  $contaje2=count($temp1);
  $temp1=str_replace(",",".",$temp1);
  $temp3=str_replace(",",".",$temp3);
  $contaje1=count($temp1);
  //print "<pre>";print_r($fecha1);print "</pre>\n";
  //print "<pre>";print_r($temp1);print "</pre>\n";
  //die();
  ?>
  <!doctype html>
  <meta charset="utf-8">
   
  <script src="http://www.d3plus.org/js/d3.js"></script>
  <script src="http://www.d3plus.org/js/d3plus.js"></script>
   
  <div id="viz" style="width: 900px; height: 300px;"></div>
   
  <script>
   
    var data = [
     <?php for($nI=0;$nI<$contaje1;$nI++){?>
      {"month": <?php echo $fecha1; ?>, "name":"<?php echo
$titulo1.$nI;?>", "value": <?php echo $temp1[$nI]; ?>},
  {"month": <?php echo $fecha2; ?>, "name":"<?php echo $titulo2.$nI;?>",
"value": <?php echo $temp3[$nI]; ?>},
  <?php } ?>
    ]
    var visualization = d3plus.viz()
      .container("#viz")
      .data(data)
      .type("box")
      .id("name")
      .x("month")
      .y("value")
      .time("month")
      .ui([{ 
          "label": "Visualization Type",
          "method": "type", 
          "value": ["scatter","box"]
        }])
      .draw()
  </script>



Dave Landry <notifications@github.com> escribió:

> Yes, that should work. Can you post your code to something like jsfiddle
> or codebin so we can help?
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[1]
>       



Vínculos:
---------
[1]  
https://github.com/alexandersimoes/d3plus/issues/454#issuecomment-199443307

Dr. José M. Veiga
Dpt. Química Agrícola, Geología y Edafología.
Universidad de Murcia.

**Comment by davelandry** [comment]
My PHP is a little rusty, but if you do this it should work for the $titulo variables:
```js
visualization
  .x("name")
  .time(false)
  .draw();
```
