### ISSUE TITLE
Error when there is a zero in the data group. 

### ISSUE THREAD

**Issue by caperneoignis** [alexandersimoes/d3plus#456]
I get an "Uncaught TypeError: vars.y2.scale.viz is not a function" or "Uncaught TypeError: vars.x2.scale.viz is not a function." depending on where the zero is in the data group. IE x2 shows up if it is in the X-axis or y2 if y-axis. So if a person has a score of zero, the program will error out instead of plotting that data point on the zero line. 
I have version 1.9.1 of d3Plus, which is downloaded from the site. This is annoying because I have a lot of data points and sometimes I get a zero in the data, which I have to program an additional check to move that zero to a 1 which can result in incorrect graphing. Please let me know if there is a fix, because I did a search and could not find a similar issue.  
sample code below:
````javascript
    var sample_data = [
      {"year": 1990, "name":"alpha", "value": 0},
      {"year": 1992, "name":"alpha", "value": 20},
      {"year": 1993, "name":"alpha", "value": 25},
      {"year": 1994, "name":"alpha", "value": 33},
      {"year": 1995, "name":"alpha", "value": 52},
      {"year": 1991, "name":"beta", "value": 36},
      {"year": 1992, "name":"beta", "value": 32},
      {"year": 1993, "name":"beta", "value": 40},
      {"year": 1994, "name":"beta", "value": 58},
      {"year": 1995, "name":"beta", "value": 13},
      {"year": 1991, "name":"gamma", "value": 10},
      {"year": 1992, "name":"gamma", "value": 27},
      {"year": 1994, "name":"gamma", "value": 35},
      {"year": 1995, "name":"gamma", "value": 40}
    ]
    // instantiate d3plus
    var visualization = d3plus.viz()
      .container("#viz")  // container DIV to hold the visualization
      .data(sample_data)  // data to use with the visualization
      .type("line")       // visualization type
      .id("name")         // key for which our data is unique on
      .text("name")       // key to use for display text
      .y("value")         // key to use for y-axis
      .x("year")          // key to use for x-axis
      .draw()             // finally, draw the visualization!
````
Please let me know if you need anything else from me. I'm running this with PHP7.0 on apache2 2.4.7-1ubuntu4. Thanks again for any help.

**Comment by davelandry** [comment]
This fix will be part of the next release. :beers:

**Comment by davelandry** [comment]
@soumikpatra1993 please post more code. In order to help, we need to see how you are importing and using the library.
