### ISSUE TITLE
Deactive Aggregation

### ISSUE THREAD

**Issue by MMTLukas** [alexandersimoes/d3plus#458]
Hi alexandersimoes! 

Is it possible to deactive the aggregation?

Currently I get with the following two points only one aggregated point, altough I never configured that.

`[{"A":300,"B":600,"color":"#11DDC6","name":600},{"A":300,"B":600,"color":"#11DDC6","name":600}]`

Looking forward for you reply!
Best regards,
Lukas

**Comment by davelandry** [comment]
This is because both data points have the same ID. I'm assuming you're setting the ID as such:
```js
d3plus.viz.id("name");
```

If you give each data point a unique ID, they will not aggregate. Something like this:
```js
[
   {"A":300,"B":600,"color":"#11DDC6","name":600,"id":1},
   {"A":300,"B":600,"color":"#11DDC6","name":600,"id":2}
]
```

Then, you could set the following to still use the "name" field for labelling:
```js
d3plus.viz()
  .id("id")
  .text("name");
```
