### ISSUE TITLE
Bubble grouping not correctly displayed

### ISSUE THREAD

**Issue by bryanph** [alexandersimoes/d3plus#459]
I was expecting behaviour similar to the grouped tree-map example when calling depth(0) on the simple bubble example. 

Instead, the bubble's sizing gets messed up, as can be seen in this example: http://plnkr.co/edit/oTiFjp?p=preview

What I have changed in the example:
* .depth(1) to .depth(0)
* Multiplied all values by 10000

Am I missing something?

**Comment by davelandry** [comment]
Bubbles are only grouped in with their parents. To get what you are trying to achieve, you need to nest everything into one large parent group: http://plnkr.co/edit/o3Tyf2FjpTeCe4jru9un?p=preview

**Comment by bryanph** [comment]
Hey Dave, thanks for your response. That is indeed what I was looking for, thanks. I'll make sure to ask my question on the google discussion forums first next time.
