### ISSUE TITLE
separate mouse events for size threshold

### ISSUE THREAD

**Issue by m-ibm** [alexandersimoes/d3plus#461]
Providing a mouse-click event handler **or** threshold=true _separately_ works fine.

However, if we implement the mouse click then the default (and expected) behavior stops working because it is replaced by our function.
User click function should not be enabled on this special rectangle (at least not by default).

We implemented a hack that looks for "d3plus_other" and behaves differently.
It seems to work on the first click, but if there are additional levels the UI is not updated. This used to work in the past, so either our hack is too simple or this functionality is broken.

**Comment by davelandry** [comment]
For reference, this is the code done internally for the threshold shapes: https://github.com/alexandersimoes/d3plus/blob/master/src/viz/helpers/shapes/draw.js#L672-L712

**Comment by davelandry** [comment]
closed in favor of #447
