### ISSUE TITLE
UI should mark the selected (clicked) rectangle

### ISSUE THREAD

**Issue by m-ibm** [alexandersimoes/d3plus#462]
Now that mouse clicks are supported users implement some logic for the click (we display a table with additional info).
Problem is that user might forget where he clicked or be unsure whether he clicked the correct rectangle. Some UI feedback is needed as to what's been selected/clicked.
A suggestion might be to change the color of the border (need to choose one that the user doesn't have).

As a best solution for now, we give our table a title matching that of the rectangle, however, for more than a couple of tens of items it is hard to "match" what was the last click visually.

**Comment by davelandry** [comment]
Could #8 be a potential solution for this?

**Comment by m-ibm** [comment]
Yes, if it does not require re-drawing the whole tree-map.
The code performing the custom mouse-click could easily also highlight current rectangle.
(a remove-all-highlights method would be nice too)
