### ISSUE TITLE
text split options for "." still not splitting

### ISSUE THREAD

**Issue by rmatejka** [alexandersimoes/d3plus#467]
I just had a chance to pull latest and revert my code to set the split array manually - but the original problem is back - not splitting on period. Am I not making the call correct?

d3plus.textwrap()
.container(nodeText)
.x(leftSideOffset)
.width(textLabelWidth)
.resize(false)
.padding(0)
.text({ value: label, split: ["-", "/", ";", ":", "&", "."] }) /// Added "." 
.draw();

**Comment by davelandry** [comment]
Closed with #427
