### ISSUE TITLE
value in bar charts

### ISSUE THREAD

**Issue by Gbeschbacher** [alexandersimoes/d3plus#468]
Hi guys,

i cannot find an option to disable the value in a bar of a bar-chart.
![example image](https://i.imgur.com/ZYie0Od.png)

how can one disable these values inside a bar?

thanks in advance :)

**Comment by fsistemas** [comment]
Bars without values: http://d3plus.org/examples/basic/32517cfde67270c99092/

A question: I need know what can i do to have values on bars?

**Comment by Gbeschbacher** [comment]
I just figured out that the following code (look at the name property) is responsible for the value inside the bar:

```
    @chartData = [
        {
            color: "#FA05AF"
            id: 0
            name: 200
            x: "Orange"
            y: 200
        },
        {
            color: "#FA05AF"
            id: 1
            name: 300
            x: "Banane"
            y: 300
        },
        {
            color: "#FA05AF"
            id: 2
            name: 400
            x: "Apfel"
            y: 400
        }
    ]

    options.headers = {x: "x", y: "y"}

    d3plus
    .viz()
    .container("#chart")
    .data(@chartData)
    .type("bar")
    .id("id")
    .text("name")
    .x(options.headers["x"])
    .y(options.headers["y"])
    .order("asc")
    .color("color")
    .width(500)
    .height(500)
    .draw()
```

The thing is: if i remove the name property, the tooltip will show the "id" property on hover and this is what i do not like. Anyone knows how to handle this? Displaying the name only on hover?

**Comment by fsistemas** [comment]
I hope this helps:

https://github.com/alexandersimoes/d3plus/wiki/Visualizations#tooltip

Remove:  .text("name")
Add Tooltip:  .tooltip( { value: ["x", "y"] }),

@chartData = [
        {
            color: "#FA05AF"
            id: 0
            name: 200
            x: "Orange"
            y: 200
        },
        {
            color: "#FA05AF"
            id: 1
            name: 300
            x: "Banane"
            y: 300
        },
        {
            color: "#FA05AF"
            id: 2
            name: 400
            x: "Apfel"
            y: 400
        }
    ]

    options.headers = {x: "x", y: "y"}

    d3plus
    .viz()
    .container("#chart")
    .data(@chartData)
    .type("bar")
    .id("id")
    .x(options.headers["x"])
    .y(options.headers["y"])
    .tooltip( { value: ["x", "y"] }),
    .order("asc")
    .color("color")
    .width(500)
    .height(500)
    .draw();

**Comment by Gbeschbacher** [comment]
well this is already close to what i want 
![example image](http://i.imgur.com/6izflbZ.png)

is there still any chance to remove the id from the tooltip?

**Comment by davelandry** [comment]
`.text( )` controls what is shown in the tooltip titles

`.labels( )`, by default, uses the `.text( )` value to label the bars. If you want to just turn the bar labels off, while keeping `.text( )` for the tooltips, just use:
```js
.labels(false)
```

**Comment by Gbeschbacher** [comment]
thank you for answering so fast and helping me out!

**Comment by davelandry** [comment]
:beers:
