### ISSUE TITLE
need feature for word-break in textwrap

### ISSUE THREAD

**Issue by geohuz** [alexandersimoes/d3plus#469]
currently the textwrap only supports word-wrap which only suite for english text. But for Asian text it doesn't work and rendering empty output. In Asian text, we need word-break which allows line breaking within words.

**Comment by davelandry** [comment]
Word-break is very difficult to detect in SVG (or at least that's my understanding). I'm investigating this feature as part of the new separate text wrapping modules, and would love some help: https://github.com/d3plus/d3plus-text/issues/8
