### ISSUE TITLE
question about subtitle size

### ISSUE THREAD

**Issue by pachamaltese** [alexandersimoes/d3plus#473]
Hi

I have enabled the  total values as titles using

```
.title({
           "total": true
          })
```

but the titles are too small and I haven't found how to change it from `d3plus.js` and I could not found an answer on forums.

Is there a solution to this?

**Comment by davelandry** [comment]
The "total" key can be passed an advanced object just like the title: https://github.com/alexandersimoes/d3plus/wiki/Visualizations#title

```js
.title({
  "total": {
    "font": {"size": 24},
    "value": true
  }
})
```
