### ISSUE TITLE
Treemap is not calculating color based on the range provided

### ISSUE THREAD

**Issue by nandininagaraj24** [alexandersimoes/d3plus#475]
I am trying to vary the color of treemap from red(incase value is negative) to green(incase value is positive) based on a parameter TotalBaseMTD. In a few scenarios, random color gets picked up.
A scenario that I have tested for:
Input:
 when TotalBaseMTD value is +ve for all
Expected Output:
  All green squares
Obtained Output:
 a blue color square and a red color square
 
Attached is the sample code:
http://jsfiddle.net/Evw3x/14/

I have seen a similar issue in grouped treemap too.

**Comment by davelandry** [comment]
The color "range" is used for scales that span from negative to positive, while the color "heatmap" is used to scales with all positive values. You just need to override the "heatmap" colors as well as the "range" colors: http://jsfiddle.net/Evw3x/15/

**Comment by nandininagaraj24** [comment]
Hi Dave,
I have tried that, it helps to stick within the range but gives the wrong color. In the fiddle that you have posted too , both the squares should be green as color parameter (TotalBaseMTD) has a positive value for both squares.

**Comment by davelandry** [comment]
I'm not sure I understand what the expected behavior is here.

When mapping 2 values to a heatmap, the smaller value will take the first color in the heatmap, and the larger value will take the last color.
