### ISSUE TITLE
When there are multiple treemaps, the color scale gets messed up

### ISSUE THREAD

**Issue by nandininagaraj24** [alexandersimoes/d3plus#477]
There is a simple treemap and a grouped treemap in this jsfiddle and when I drill down the grouped treemap, the color scale below the graph or both treemaps change.

http://jsfiddle.net/Evw3x/17/

In my actual application, I have multiple treemaps, Is there a way of preventing all the color scales from varying all  the time?

**Comment by nandininagaraj24** [comment]
I modified line 27286 from 
var heatmap = scale.selectAll("#d3plus_legend_heatmap")
to 
var heatmap = scale.select("#d3plus_legend_heatmap")
which solved this issue of multiple treemaps being updated

**Comment by davelandry** [comment]
@nandininagaraj24 thanks for finding this! Turns out it was a problem with conflicting IDs. I've not made each heatmap use a distinct ID, and they no longer overwrite eachother.

Will be available in the next release.
