### ISSUE TITLE
Multiple <rect> with wrapped <text>

### ISSUE THREAD

**Issue by ebwalker** [alexandersimoes/d3plus#479]
I noticed that rectResize uses an ID instead of a class. If I have multiple <rect> followed by <text>, would it be possible to have text wrap in each rectangle?  

Here is the codepen I was playing with earlier today. http://codepen.io/ebwalker/pen/RadMWX

**Comment by ebwalker** [comment]
I was able to get it to work on multiple shapes by giving the text on each shape a distinct class of it's own and setting the y offset. Then repeating the js for each class. 

I'll admit that I am really new to javascript and pretty much hacking my way around so it is not as clean as it could be. But it functions. Anyone else have a better way?

http://codepen.io/ebwalker/pen/ZWZYEq

**Comment by davelandry** [comment]
Your second example is the correct intended use of the `d3plus.textwrap( )` method. One shape at a time.

That being said, the currently in development standalone [d3plus-text](https://github.com/d3plus/d3plus-text) module might suit your fancy, as it does support multiple data points at once (but does not currently detect bounds from SVG elements).
