### ISSUE TITLE
Changing Range on Y Axis Draws Bars over the X Axis

### ISSUE THREAD

**Issue by Carrie0302** [alexandersimoes/d3plus#480]
When I change the "range" on my y-axis it changes the axis values, but not the value of the bar chart so the bars are drawn over the x axis.    In my example I want to change the y axis so the bar chart starts from 5 rather then 0. I played around adjusting the domain to see if this was the issue, but I am a newbie so this might boil down to my misunderstand of domains and ranges in D3.
`.y({
			        "label": ""+ uniqueVal_IndicatorInfo[0].LongName+ " (" + uniqueVal_IndicatorInfo[0].Unit +")",
			        "domain" : [5, 12],
			        "range": [5, 12],
			        "scale": "linear",
			      	"value": "Value"`

**Comment by davelandry** [comment]
@Carrie0302 thanks for finding this, it will be included in the next release.

**Comment by paulofelipe** [comment]
Dave, after this change is not possible to use the old behavior anymore? Draw negative bars from zero line like this example: https://jsfiddle.net/paulofel/ykcbse2L/

In this new version the result is: https://jsfiddle.net/paulofel/t0dwapsq/

I opened a topic in d3plus google group, but I don't know where is more appropriate to discuss this issue.

Thanks.

**Comment by davelandry** [comment]
yikes, that's my bad. I'm fixing this now and it will be part of the next release.

definitely a bug, this is the right place to post it. I would say this even warrants it's own issue: https://github.com/alexandersimoes/d3plus/issues/485
