### ISSUE TITLE
Scatterplot - Circles drawn on panel border.

### ISSUE THREAD

**Issue by paulofelipe** [alexandersimoes/d3plus#487]
The new version of d3plus (v1.9.4) created a problem in scatterplot charts. The circles are outside of the panel. 

Examples:
http://d3plus.org/examples/advanced/9861345/
http://d3plus.org/examples/advanced/9925661488cdc1828a2c/

The behavior in v 1.9.3 was different.

Thanks!

**Comment by davelandry** [comment]
good find, sorry about that. will be fixed with the next release.
