### ISSUE TITLE
Color the edges of networks individually

### ISSUE THREAD

**Issue by danielhomola** [alexandersimoes/d3plus#490]
Could you please let me know where in the source the color of the network edges is set, so I can play around with it.. Looks like this feature hasn't been implemented yet but it'd be a must for me.. Is this relatively easy to do?

Cheers,
Daniel

**Comment by danielhomola** [comment]
Realized I can hack my way around this with 
`.edges({
                "color": function(e) {
                    return colorScale(e.strength);
                },
                "opacity":0.65,
                "value": connections
            })`

where colorScale is just a regular d3 linear gradient, and strength is an extra param in my connections.

**Comment by davelandry** [comment]
Glad you figured out a work around!

This is a duplicate of #71
