### ISSUE TITLE
nodes of network disappear if redrawn

### ISSUE THREAD

**Issue by danielhomola** [alexandersimoes/d3plus#491]
Hi,

First of all thanks again for this amazing library, it's awesome!

I've made a network visualisation back in June 2015, using the version of d3plus of the time. It has a network that could be filtered with a heatmap. The heatmap and the network show the same data but in different ways, and by selecting a region of the heatmap the network gets filtered to only show the relevant nodes. Check it out here: http://danielhomola.com/bariatric_network/
You can click the heatmap, drag your mouse and select an area of the heatmap to filter the network. If you then click on a white cell of the heatmap or make an empty selection, the network goes back to full.. 

This is done on the backend by using .filter() on the underlying arrays, passing those to a function that redefines the network's nodes, edges, and data methods and finally calls draw().

As you can see it used to work pretty nicely with the old d3plus, but now that I updated to the latest 1.9.5 version, all the nodes disappear once I go back to the full network. I checked in the console and the network gets all the right data, nothing changed in my code only d3plus got updated.. The network is there, the edges are there but the nodes are simply blank.

Do you have any idea what could have gone wrong? Thanks so much for your help!

Daniel

**Comment by danielhomola** [comment]
Sorry my bad, found something I changed.. Shouldn't have done that.. Thanks anyway!

**Comment by davelandry** [comment]
:beers:
