### ISSUE TITLE
Line chart x axis broken

### ISSUE THREAD

**Issue by mjsarfatti** [alexandersimoes/d3plus#502]
Please see the JSFiddle: https://jsfiddle.net/2x56udvz/

As you can see a few values of the x axis get reshuffled and the whole graph brakes down. I couldn't find a single reason for this. It looks like the second value of the scale is sent to the middle, and the middle value to the end of the scale?

The bug was introduced with version 1.9.4

**Comment by davelandry** [comment]
Can you post a screenshot of what you're seeing? If my understanding of your data structure is correct, the chart looks ok to me.

**Comment by mjsarfatti** [comment]
Ok I checked with 3 browsers and they all interpret the data differently. Please note that I'm treating dates as primitive strings, and not as Date objects (nor timestamps), the expected outcome is the one in Safari. No idea of what is going on, maybe some browsers try to interpret the strings as Dates?

**CHROME**
![schermata 2016-06-24 alle 10 25 50](https://cloud.githubusercontent.com/assets/736316/16332430/263a515e-39f6-11e6-9b93-43f0832a2218.png)

**FIREFOX**
![schermata 2016-06-24 alle 10 28 26](https://cloud.githubusercontent.com/assets/736316/16332499/7ffb9d42-39f6-11e6-8cbe-19262f0ffbac.png)

**SAFARI**
![schermata 2016-06-24 alle 10 28 37](https://cloud.githubusercontent.com/assets/736316/16332504/8a800730-39f6-11e6-81bb-e9d4f4d0aeba.png)

**Comment by mjsarfatti** [comment]
In this fork: https://jsfiddle.net/nrwg8tLq/ I substituted the dates for 100% non ambiguous strings. I also made sure the "total" were never 0. The problem persists though...

**Comment by mjsarfatti** [comment]
Hello, 
have you been able to take a look at the issue?
If not, any direction you can point me to? I could be able to do something about it.
Thank you for your time!

**Comment by davelandry** [comment]
turns out it was a difference in how each browser sorts javascript strings. I've pushed a catch for more robust string sorting, and it will be part of next release.

in the meantime, if you set `.time("date")` it will sort your axis correctly (and give you a neat little timeline)
