### ISSUE TITLE
incorrect resizing when .height() set to small number

### ISSUE THREAD

**Issue by c1nco** [alexandersimoes/d3plus#503]
Graph doesn't correctly resize when .width() sets graph into "small mode"

Working resize -- http://jsfiddle.net/vchhwwh6/1/
Broken resize -- http://jsfiddle.net/hw9314or/1/

	var data = [
		{"name":"total", "time": 15},
		{"name":"male", "time": 10},
		{"name":"female", "time": 5},
	]
	var visualization = d3plus.viz()
		.container("#viz")
		.data(data)
		.height({"value":85,"max":85})
		.type("bar")
		.id("name")
		.x({"value" : "time", "label" : false, "labels" : false, "grid" : false})
		.y({"value": "name", "label" : false, "labels" : false, "grid" : false})
		.y({"scale": "discrete"})
		.axes({"ticks": false})
		.resize(true)
		.draw()

**Comment by davelandry** [comment]
You're specifically referring to the margins not going away, correct?

**Comment by c1nco** [comment]
.height() wooops, thanks for correcting.

Actually the problem I notice is that the rect's/shapes aren't adjusting widths etc when resizing.
