### ISSUE TITLE
Inner div created with pixel size when actually parent was percentage sized

### ISSUE THREAD

**Issue by dznicol** [alexandersimoes/d3plus#504]
The div element that I am initialising d3plus onto is defined as:

```
<div id="my-chart">
```

With CSS:

```
#my-chart {
    width: 100%;
    height: 100%;
}
```

When I initially call d3plus.viz/draw a new inner div is created as:

```
<div id="my-chart">
    <div style="position: relative; width: 100px; height: 100px;">
```

If change my div to be width/height 200% as in:

```
#my-chart {
    width: 200%;
    height: 200%;
}
```

Then the inner div that is created by d3plus is:

```
<div id="my-chart" campaign-spot-chart data-category="weekday">
    <div style="position: relative; width: 200px; height: 200px;">
```

So I am pretty sure that the inner div is using the percentage dimensions as pixel dimensions.

If I call d3plus.draw on the element again then the issue goes away and I get an inner div properly sized into my Bootstrap cells as something like (depending on current width/height of browser):

```
<div style="position: relative; width: 360px; height: 360px;">
```

Am I doing something wrong or could this be an issue using percentage div sizing?

Thanks in advance,

David

**Comment by davelandry** [comment]
can you post your javascript code where you're initializing and drawing the d3plus.viz?

**Comment by dznicol** [comment]
Hi, sorry I should have updated, my div was hidden when I was seeing jquery return 100 for width/height. Once the tab containing the viz is visible on screen, I now do a redraw and everything works fine (apart from a little flash as the viz resizes - but I could avoid that by not calling draw until the div is visible).

**Comment by davelandry** [comment]
Ahh gotcha. Yeah, if the div is hidden, you either need to wait until it's visible to call draw or manually set the width and height methods.
