### ISSUE TITLE
[Feature Request] Sorting ticks in barchart

### ISSUE THREAD

**Issue by pachamaltese** [alexandersimoes/d3plus#505]
Hi

I'd like to see in a future version this kind of option: If my x-axis comes from a factor variable (e.g. good quality and bad quality in the x-axis and the observed frequency of each type in the y-axis) then I'd like to:
- Sort to x-axis ticks in the same order as in the data 
- Sort the x-axis ticks alphabetically or according to the y-value so that the chart describes a half U shape

**Comment by curran** [comment]
I believe you can already do this, by setting the sorted values as the domain of an ordinal scale.

**Comment by pachamaltese** [comment]
Thanks !!!

I didn't find that in Google

**Comment by pachamaltese** [comment]
There was a reply here that now is missing

> Curran Kelleher <notifications@github.com>
> 6:09 (hace 7 horas)
> 
> para alexandersimoe., mí, Author 
> 
> I believe you can already do this, by setting the sorted values as the domain of an ordinal scale.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

In other words, how do I pass 

```
var x = d3.scale.ordinal()
    .domain(["A","B","C"])
    .rangePoints([0, width]);
```

to d3plus?

**Comment by curran** [comment]
Yes, sorry about that. I mistakenly thought this was an issue on the D3 project itself when I posted that, and when I realized it was an issue in d3plus, I deleted the reply.

In raw D3, the ordinal scale domain will dictate the ordering that appears on the axis.

However, I'm not so familiar with D3Plus actually, and I'm not sure how to expose this functionality within the abstraction that D3Plus provides, so I deleted the comment. I'm not sure how it can be done in D3Plus. Good luck though!

**Comment by pachamaltese** [comment]
no worries, I still don't figure out a solution

—————

*Mauricio Vargas Sepúlveda 帕夏*

2016-07-01 15:02 GMT-03:00 Curran Kelleher <notifications@github.com>:

**Comment by davelandry** [comment]
You can manually set a scale's range using:
```js
.x({"range": [0, 1, 2, 3]})
```

You can override the sorting algorithm by using the `.order( )` and either passing a separate key with each data point that corresponds to it's sort order (then saying `.order("your-key-name")`) or by passing a custom function to the method.
