### ISSUE TITLE
mirrored barchart v1.9.3

### ISSUE THREAD

**Issue by pachamaltese** [alexandersimoes/d3plus#507]
Hi

At some resolutions the barcharts looks like this

![screenshot 2016-07-01 at 6 32 26 pm](https://cloud.githubusercontent.com/assets/10091065/16570467/ba04f64e-4213-11e6-83b2-43a70982d290.jpg)

**Comment by davelandry** [comment]
this was reported in #485 and the fix will be part of the next release
