### ISSUE TITLE
Show only Primary connection in rings chart

### ISSUE THREAD

**Issue by ssjsatish** [alexandersimoes/d3plus#521]
I have following connection
`var connections = [{ "source": "alpha", "target": "beta"},{ "source": "alpha", "target": "gamma"},
{ "source": "beta", "target": "delta"}, { "source": "beta", "target": "epsilon"},
{ "source": "gamma", "target": "tau"},{ "source": "gamma", "target": "zeta"},
{ "source": "gamma", "target": "theta"},{ "source": "eta", "target": "gamma"},
{ "source": "iota", "target": "mu"},{ "source": "iota", "target": "gamma"},
{ "source": "kappa", "target": "beta"},{ "source": "lambda", "target": "beta"},
{ "source": "lambda", "target": "mu"},{ "source": "lambda", "target": "upsilon"},{ "source": "kappa", "target": "nu"},        { "source": "pi", "target": "sigma"},{ "source": "pi", "target": "delta"},{ "source": "delta", "target": "rho"},        { "source": "rho", "target": "xi"},{ "source": "xi", "target": "psy"},{ "source": "psy", "target": "phi"},
        { "source": "phi", "target": "tau"},{ "source": "tau", "target": "omega"}];`
I want to show only primary connection to the titled source i.e if `Alpha` is main node then it should show only `Beta` and `Gamma` and if `Gamma` is centered node then chart should show only those nodes who are connected to `Gamma`
I tried with following
`var visualization = d3plus.viz()
        .container("#viz")
        .type("rings")        
        .edges({ "value": connections, "arrows": 10,"limit":2 }) 
        .id({ "solo": "alpha" })        
        .focus('alpha')
        .draw()`
but not getting what is require.
[POCTest.zip](https://github.com/alexandersimoes/d3plus/files/371268/POCTest.zip)
Any help is highly appreciated.

**Comment by ssjsatish** [comment]
So I was going through the code and commented the `secondaries` nodes which was being creating a list of secondary connection and got it working as required but only problem remaining is that the primary connections are closely placed right now I'm trying to make the edge length little bit lengthier so that primary connections get more clearly visible because the original data set has lots of primary connections. What specific code segment I should concentrate on.

**Comment by davelandry** [comment]
Closing this in favor of #205 

In order to implement this, we'll need to generalize the 2 functions that currently generate the primary and secondary connections in order to allow n-number of degrees.
