### ISSUE TITLE
slack channel for d3plus

### ISSUE THREAD

**Issue by heenamahour** [alexandersimoes/d3plus#522]
Hi

It will be great to have the d3plus community available on slack. It will help it grow, develop and learn more efficiently by improving team communication :)

Suggestions?

**Comment by davelandry** [comment]
I have no problem setting this up (and linking to it from the repo) if there's enough interest.

**Comment by heenamahour** [comment]
Yay !! Would be happy to have it ! :)
Thanks @davelandry You rocks !

**Comment by davelandry** [comment]
Alright, I just set up http://d3plus-chat.slack.com

It's invite only, right? For now I don't mind inviting people who comment with their e-mail address here, but we should probably set up a Google Form or something as a sign up sheet.

Does anyone know something that fits this use case better than manually checking a Google Form?

**Comment by davelandry** [comment]
I've created a simple sign up form, and added a badge to the README.

https://goo.gl/forms/ynrKdvusekAwRMPf2
