### ISSUE TITLE
Is there a way to retrieve legend's min/max values?

### ISSUE THREAD

**Issue by m-ibm** [alexandersimoes/d3plus#523]
... or the whole array of values used for the legend?
Calling `treeMap.data()` returns all data objects and `treeMap.legend()` returns only `true`.

**Comment by davelandry** [comment]
It's currently hidden away in the .color( ) method, accessible via:
```js
viz.color(Object).valueScale.domain()
```

When you pass the literal `Object` to any method, you get returned all of the internal stored variables for that method, which closely map to what you're able to pass as advanced configuration.

However, there currently isn't any override for the domain of the scale. Which I think there should be and shouldn't be too hard to implement.

As a sidenote, you can override the color range by modifying either the "heatmap" or "range" option:
```js
viz.color({
    heatmap: ["red", "white", "green"], // the colors used for all positive or all negative domains
    range: ["red", "black", "green"] // the colors used for domains that cross 0
})
```

**Comment by davelandry** [comment]
Done. Will be part of next release. Override like this:
```js
viz.color({domain: [10, 40]);
```

Recognize that domain? 😉 (#509)

**Comment by m-ibm** [comment]
Only issue with the suggested solution/workaround to get the domain is that I have to somehow know when the tree-map finished drawing.
Before that `valueScale` is undefined.
Not an issue at the moment as I use this inside `"number"` to change the label for the first/last tick (and display nothing in between).
