### ISSUE TITLE
.time() breaks stacked bar chart ordering

### ISSUE THREAD

**Issue by lcoursey** [alexandersimoes/d3plus#536]
Really loving d3plus, thanks! However:

I'm struggling to get my stacked bar chart to order correctly when using the time slider. 

Stack ordering works correctly in this [jsfiddle example](http://jsfiddle.net/skfdk1ao/4/), ordered by country.

However if you uncomment the line **.time("year")** the ordering breaks. 

Uncommenting the line also seems to stop the chart rendering in Firefox (48.0) - it's stuck at "drawing visualization". But seems fine in IE.

**Comment by davelandry** [comment]
Thanks for the kind words!

The incorrect stacked ordering has been reported here: #527 

It looks like the Firefox issue has to do with the trailing space after your year strings. If you remove that, it works fine. All time variables get parsed as a javascript Date object, so I'm guessing Firefox isn't as lenient as the other browsers.
