### ISSUE TITLE
static line issue on bar chart

### ISSUE THREAD

**Issue by ihlarry** [alexandersimoes/d3plus#537]
I'm trying to get the "lines" key to work such that the static line drawn is a solid line, not a dashed line. Also, I can't get the line to be labeled even though the documentation suggests it can be labeled.

![screen](https://cloud.githubusercontent.com/assets/16769895/17815217/49b69c28-6601-11e6-9010-d84636558b74.PNG)

The code that I have is for building a stacked bar chart. The bar chart builds fine and this code works for the y-axis works, but how can static line be solid and how to add label to static line?

.y({"stacked": true, "value": "Amt ($)", "range": [0,40000], "lines": {"value": totalmedicalcost, "font": {"size": "10px"}, "color": "#063D2E","width": "3px"}})

**Comment by davelandry** [comment]
Sorry, the documentation's not so clear with this one, here's what you need to do:

```js
.y({
  lines: {
    dasharray: "0", 
    font: {size: 10},
    width: 3,
    value: [{text: "My Label", color: "#063D2E", position: totalmedicalcost}]
  }
})
```
