### ISSUE TITLE
stack plot share axis problem in 1.9.8

### ISSUE THREAD

**Issue by csaladenes** [alexandersimoes/d3plus#540]
When we have a stack plot in the latest release 1.9.8, the share axis type is broken, just shows 1/n for each entry.

http://jsbin.com/caqobazaze/edit?html,output

**Comment by davelandry** [comment]
Not sure I'm seeing the problem. Here's an edit of your jsbin with the share axis: http://jsbin.com/zusapuwofa/edit?html,output

I also noted you were padding `["name","name"]` to .id( ). No need for the repetition.
