### ISSUE TITLE
Removing frameborder?

### ISSUE THREAD

**Issue by voltdatalab** [alexandersimoes/d3plus#553]
This is an awesome tool, thank you for this. 

Is there any way to remove that persistent frameborder from the bar chart (especially on the right)?

Here is an example: http://codepen.io/voltdatalab/pen/JRJaoJ?editors=1010

**Comment by davelandry** [comment]
https://github.com/alexandersimoes/d3plus/wiki/Visualizations#axes

```js
.axes({
  background: {
    stroke: {
      width: 0
    }
  }
})
```
