### ISSUE TITLE
grouped pie chart click events are broken

### ISSUE THREAD

**Issue by nalhadad** [alexandersimoes/d3plus#558]
The pie workes perfectly as a grouped TreeMap (drill down), but when we have more than 300 lines of data the pie is blocked and it does not work anymore.

**Comment by davelandry** [comment]
please post a [jsfiddle](https://jsfiddle.net/) showing the issue

**Comment by nalhadad** [comment]
Thank you for Your answer.
Here is an example: https://jsfiddle.net/3c3ff7jj/6/.
In this example if we choose the type as treemap and not pie, it works perfectly but with a pie it is blocked on the second level (type Date). 
If we reduce the quantity of the Data, it works in the type pie.

**Comment by nalhadad** [comment]
Still waiting for an answer
thank you

**Comment by davelandry** [comment]
This fix will be part of the next release. :beers:
