### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element':

### ISSUE THREAD

**Issue by tloy1966** [alexandersimoes/d3plus#559]
Thanks to d3plus.

I using nested tree_map, in depth=3, error and show following message.

> Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element': 'text#d3plus_label_板橋區_公寓5樓含以下無電梯_住家用_新北市板橋區國泰街61~90號_rect' is not a valid selector.

Is this language support issue? or string parse issue?

Here is demo [http://rpwebcore10.azurewebsites.net/](url)

Here is code
`<script>
    var _data = {};
    $.get('Home/GetData', function (data) {
        _data = data;
        console.log(_data);
        drawDiv1(data);
    });
    function drawDiv1(data)
    {
        var visualization = d3plus.viz()
    .container("#viz")
    .data(data)
    .type("tree_map")
    **.id(["district", "buitype", "pbuild","location"])**
    .size("uprice")
      .time("year")
    .color("uprice")
    .ui([
      {
          "method": "size",
          "value": ["uprice", "farea"]
      },
      {
          "method": "color",
          "value": ["uprice", "farea"]
      }
      ])
    .draw()
    }
</script>`

**Comment by davelandry** [comment]
This fix will be part of the next release. :beers:
