### ISSUE TITLE
network labels are too big in Chrome (D3Plus v1.9.8 & v2.0)

### ISSUE THREAD

**Issue by pachamaltese** [alexandersimoes/d3plus#561]
Hi

I'm still having the same issue described [here](https://github.com/alexandersimoes/d3plus/issues/531#issuecomment-239520375) with D3Plus v2.0

This only happens in Chrome (Safari is ok)

**Comment by davelandry** [comment]
Please share a sample of your 2.0 code as an issue in the corresponding 2.0 repo: https://github.com/d3plus
