### ISSUE TITLE
Automatic network node positioning broken

### ISSUE THREAD

**Issue by ajyoon** [alexandersimoes/d3plus#563]
Automatic network positioning (using the exact code at http://d3plus.org/examples/advanced/9956648/ but swapping `script src=` for local dev branch) throws a TypeError at `src/core/parse/nodes.js:13` with message `TypeError: vars.nodes.value.filter is not a function`. A closer look reveals that `vars.nodes.value` is a boolean `false`.

The exact commit which broke this was f41d7eb. 

I spent a while poking around trying to figure out how the type leak was being tripped by the f41d7eb, which allowed `edges` to be omitted, but haven't had any success. I suspect the culprit is in `src/viz/types/networks.js`, but the fact that the TypeError pops up in a completely different place makes it hard to tell. Would appreciate a look from someone more familiar with the codebase!

**Comment by davelandry** [comment]
Thanks for the thorough bug report! Was able to find the culprit, and the fix will be part of the next release. :beers:
