### ISSUE TITLE
color with small values crash browser in pie chart

### ISSUE THREAD

**Issue by MonTty** [alexandersimoes/d3plus#565]
this works 
  var data = [
    {"value": 0.1, "name": "beta"},
  ]

when add the color dont work 
  var data = [
    {"value": 0.1, "name": "beta", "color": "#80D066"},
  ]

here is an example

https://jsfiddle.net/ImMonTty/5z38hh7v/

**Comment by davelandry** [comment]
seems to be related to #558 and will be fixed as part of the next release
