### ISSUE TITLE
v4 circular textwrap

### ISSUE THREAD

**Issue by cocomo** [alexandersimoes/d3plus#570]
Please: I have a dynamic forced bubble layout operating on d3 v4. Is there a chance to see d3plus beautiful textwrap functionality in there? 

I was able to tweak d3plus missing reference to d3.scale.ordinal by creating 

`d3.scale = {};
d3.scale.ordinal = d3.scaleOrdinal;`

right before loading d3plus.org/js/d3plus.js.

Now text wrapping performs nice and smooth, but when i add a call to resize(true) the following error comes up:

> TypeError: tspans.enter(...).append(...).text(...).style(...).attr is not a function

[https://jsfiddle.net/cocomooo/5k26pnhd/1/](https://jsfiddle.net/cocomooo/5k26pnhd/1/)

I also tried d3plus-text but could not get it to work with d3 v4. To me it seems d3plus-text is still far away from what the d3plus textwrap() does?

**Comment by davelandry** [comment]
The [d3plus-text](https://github.com/d3plus/d3plus-text/issues?q=is%3Aissue+is%3Aclosed) module is pretty close to the current featureset of the 1.0 function. It actually already has better wrapping detection, but no circle wrapping yet.

Once we've got that baked in, you should be good to go. The d3plus v2 modules are meant to be used with d3 v4, and I have no current plans of porting the original d3plus v1 codebase over to d3 v4. Therefore, I'm closing this issue in favor of https://github.com/d3plus/d3plus-text/issues/5
