### ISSUE TITLE
.csv() download with firefox browser

### ISSUE THREAD

**Issue by taroongunessee** [alexandersimoes/d3plus#578]
The .csv() function call is apparently not working with Firefox browser.

Here is the fiddle link: https://jsfiddle.net/3415pvg2/1/

It works fine in Chrome.

Any help on this please?  Thanks

**Comment by ilidio** [comment]
I just made a small fix:
https://www.dropbox.com/s/wnf6fa51ohbvjhy/d3plus.full.js?
This fix is based in what I read about: **Use JavaScript to Export Your Data as CSV**
@ https://halistechnology.com/2015/05/28/use-javascript-to-export-your-data-as-csv/


The fix only consist's in chaning the code, where he tries to download the CSV:
// Line 38994
 var blob = new Blob([csv_data], {type: "text/csv;charset=utf-8;"});
        var link = document.createElement("a");
        if (link.download !== undefined) {
            var url = URL.createObjectURL(blob);
            link.setAttribute("href", url);
            link.setAttribute("download", title + ".csv");
            link.style = "visibility:hidden";
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }

**Comment by ilidio** [comment]
There was bug relative responsive feature. I just added a new var to control that. Check the file attached in
[d3plus.full.js.zip](https://github.com/alexandersimoes/d3plus/files/1333920/d3plus.full.js.zip)

**Comment by davelandry** [comment]
@ilidio great find! if you create a Pull Request with the changes made directly in the source code, I can review and merge into the project.

The source file can be found here: https://github.com/alexandersimoes/d3plus/blob/8b41b2e69aba349a2248123ba4c932d41512c3eb/src/viz/methods/csv.coffee

**Comment by ilidio** [comment]
Hi,
I will do. 
Do I need any kind of permission?

Greetings

**Comment by ilidio** [comment]
I just made that correction:
https://github.com/ilidio/d3plus/blob/master/src/viz/methods/csv.coffee
Is this correct?

**Comment by ilidio** [comment]
Do I need to be a collaborator in your projecto?
