### ISSUE TITLE
Rings: Label truncated when name contains blanks and first word is too short

### ISSUE THREAD

**Issue by Michael-E-Rose** [alexandersimoes/d3plus#583]
When the label of a node is human name with a short first name, it gets truncated, which looks very ugly. Even when the entire name is longer, it does not get truncated when the first name is longer, too. Instead, it just decreases the fontsize.

http://jsfiddle.net/merose/7n4yym55/

**Comment by davelandry** [comment]
renders fine for me:

<img width="415" alt="screen shot 2017-06-04 at 11 01 36 pm" src="https://cloud.githubusercontent.com/assets/1847581/26769050/dfe535d6-4979-11e7-824a-28db6b647cc4.png">


@Michael-E-Rose please post your system and browser information, along with a screenshot of what you are seeing.

**Comment by Michael-E-Rose** [comment]
I also now see what you see, i.e. nothing is truncated. I tested with Chrome and Firefox on Ubuntu. Maybe it was a browser issue.
