### ISSUE TITLE
Specifying a palette/theme

### ISSUE THREAD

**Issue by markwalsh-liverpool** [alexandersimoes/d3plus#590]
Is it possible to specify a theme/palette across all visualisations using this library?

**Comment by azastupailo** [comment]
@markwalsh-liverpool maybe [`.config()`](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#config) method will be useful for you?

https://jsfiddle.net/ssw7a1mz/

**Comment by markwalsh-liverpool** [comment]
Yep that works for me, thanks!
