### ISSUE TITLE
Order data in a stacked bar chart

### ISSUE THREAD

**Issue by ltoole** [alexandersimoes/d3plus#592]
Is there a way to set the vertical order of the data shown in a stacked bar chart? The legend can be sorted, but what about the vertical order across all bar charts?

**Comment by azastupailo** [comment]
@ltoole check [this](https://groups.google.com/d/topic/d3plus/VTikKjClu8Y/discussion) Google group discussion. I think the same problem was solved.

**Comment by davelandry** [comment]
the stack ordering is currently determined by the order of the data array.
