### ISSUE TITLE
Adding more behaviour to click events on rings viz

### ISSUE THREAD

**Issue by lambdamusic** [alexandersimoes/d3plus#605]
Hi, 

I'm using the rings visualization but would like to add more actions to the viz when users click on a node and put it into focus. 

I've tried using this code, but it overrides the default click event behaviour which is not what I want.

```
.mouse({
    "click": function(d, viz) {
        console.log("clicked!");
    }
})
```

Any help would be greatly appreciated.. (btw I also thought of tackling this problem using a double click event, but I don't think that's currently supported right?)

**Update**

Just found out you can 'return true' to continue execution from the [google forum](https://groups.google.com/forum/#!topic/d3plus/QKxqXhbKOlQ) 

```
.mouse({
    "click": function(d, viz) {
        console.log("clicked!");
        return true;  // execution will continue as normal
    }
})
```

But I have a related question: from the 'd' object how do I find out if the current node is already in focus? (= at the centre of the ring, following a previous click event)

**Comment by davelandry** [comment]
calling `.focus()` on your visualization will return the current focus node id.
