### ISSUE TITLE
Assign custom attributes with D3plus

### ISSUE THREAD

**Issue by cnavarreteliz** [alexandersimoes/d3plus#612]
Hi guys! What's the equivalent to ".attrs()" function in v1.9.8?

Ex. http://d3plus.org/examples/advanced/66348d56ea386c3396fd/

**Comment by davelandry** [comment]
@cnavarreteliz the new 2.0 modules do not have an equivalent `.attrs()` method. It was removed for 2 reasons:
* it was very hard to manage and generalize internally inside of d3plus
* in development, we found that managing a global attribute *Object* on a per project basis with accessor functions for d3plus was easier
