### ISSUE TITLE
Not able to load data from external csv file in d3plus-react. In network, message displayed as "You need to enable JavaScript to run this app."

### ISSUE THREAD

**Issue by sanchamp** [alexandersimoes/d3plus#616]
import React, { Component } from "react";
import { LinePlot } from "d3plus-react";
import { csv } from "d3-request";

class Timedown extends Component {
  state = {};

  componentDidMount() {
    csv("./data/d3plus.csv", (error, data) => {
      if (error) {
        this.setState({ loadError: true });
      }

      this.setState({
        data: data.map(d => ({ ...d, x: Number(d.sec), y: Number(d.Value) }))
      });
      console.log(data);
    });
  }

  render() {
    if (this.state.loadError) {
      return <div>couldn't load file</div>;
    }
    if (!this.state.data) {
      return <div />;
    }
    const { data } = this.state;
    console.log(data);
    const config = {
      data,
      x: "sec",
      y: "Value",
      text: "Name"
    };
    return data ? <LinePlot config={{ data }} /> : <p>No Data!</p>;
  }
}

export default Timedown;

**Comment by davelandry** [comment]
closed from https://github.com/d3plus/d3plus-react/issues/13
