### ISSUE TITLE
Topojson map file does not render properly , while it renders perfectly on mapshaper.

### ISSUE THREAD

**Issue by PadamSethia** [alexandersimoes/d3plus#622]
Here is what is being rendered by d3
![](https://screenshots.firefoxusercontent.com/images/186f51a8-b665-4717-b276-7af6f27e9464.png)

And this is the render from mapshaper

![](https://screenshots.firefoxusercontent.com/images/2c1293c2-2083-4194-971a-bfd86dfa8c36.png)

Here's the code  : 
`
	var vizz = d3plus.viz()
		.container("#viz")
		.coords("./states(1).json")
		.type("geo_map")
		.id("ST_NM")
		.text("ST_NM")  
		.draw()
`
Please help to solve this issue.
Thanks !

**Comment by davelandry** [comment]
@PadamSethia I'm unable to troubleshoot without the contents of your `./states(1).json` file. Please re-open and comment with that and/or a [jsfiddle](https://jsfiddle.net/) showing the error.
