### ISSUE TITLE
IE11 not supporting string.includes

### ISSUE THREAD

**Issue by ft-lie** [alexandersimoes/d3plus#625]
Hi

Some of the demos does not work well on IE11, e.g.
https://d3plus.org/examples/d3plus-hierarchy/selecting-container/

it seems like the issue is String not supporting method 'includes'.

A workaround may be 
https://stackoverflow.com/questions/31119300/ie11-object-doesnt-support-property-or-method-includes-javascript-window 

or 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

**Comment by davelandry** [comment]
@ft-lie thanks for reporting. moved to d3plus/d3plus-dev#55 where it will be fixed
