### ISSUE TITLE
How can I control the circle size on scatter plots?

### ISSUE THREAD

**Issue by mac471** [alexandersimoes/d3plus#631]
I am plotting several hundred points using the scatter plot functionality and I want to be able to control the circle size. Specifically, I want to show the points as "dots" (i.e. very small circles) and allow the user to inspect the value by hovering over them. Instead, what happens is that all of the circles overlap each other (and the axes).  The size of the circles is controlled by the .size() variable but I can't set a reference size, e.g. the "value" 10 is a 5 px radius circle.

I can make all of the circles the same size by using a unique value for the .id() field and the same value for the variable I specify in .size() but I can't control the absolute size of the circle.

See this fiddle for an example of what I mean:  https://jsfiddle.net/mac471/pwyf3soh/  In this fiddle, Beta and Alpha overlap each other. I want to control the circle size so that they don't.

I've looked through the documentation and the closest thing that I came across is the "overlap" key in .nodes() but this appears not to apply to scatter plots.

I even went so far as to create an extra "data point" that had a large "size" value in order to force all of the other points to be a smaller size (and placed outside of the axes ranges) but this hack runs into other problems.

Thanks in advance for any pointers.

**Comment by davelandry** [comment]
@mac471 you can pass an static value as `.size(10)`, and that will become the static pixel size of the circles: https://jsfiddle.net/pwyf3soh/6/

**Comment by mac471** [comment]
Thanks Dave - perfect.
