### ISSUE TITLE
Custom font-family and font-size in Treemap

### ISSUE THREAD

**Issue by voltdatalab** [alexandersimoes/d3plus#632]
I am having a really hard time to figure out how to apply custom font-family and font-size and other customizations specifically to the Treemap layout in the new version. 

In the last version, all I needed to do to change that was something like that: 

`d3plus.viz().font({"family": "Inconsolata"})`

Now, I can't figure out. I tried to apply the textWrap function, but I should be doing something wrong. Do you have some examples on how that is working for v2?

**Comment by davelandry** [comment]
@voltdatalab I've made an example showing the behavior in the new 2.0 visualizations: http://d3plus.org/examples/d3plus-hierarchy/custom-font/

The nested config objects can be a little tricky to wrap your ahead around at first, but in the end they allow for complete customization.

**Comment by ejsandoval** [comment]
@davelandry Hi! I was using the same code of the TreeMap example with other charts of the library and the shape configuration doesn't seem to work on charts like a Bar Chart or a Scatter Plot, it only affects the legend's font-style.

![captura de pantalla 2018-03-01 a la s 19 18 33](https://user-images.githubusercontent.com/8853646/36872844-700eea46-1d85-11e8-8778-2b5b32790a72.png)

**Comment by davelandry** [comment]
@ejsandoval you may need to override the specific `Bar` object labels like this:

```js
.shapeConfig({
  Bar: {
    labelConfig: {
      fontFamily: "serif",
      fontMax: 100
    }
  }
})
```

As for the axes, you'll need two overrides for each axis, one for the title and one for the ticks:

```js
.xConfig({
  shapeConfig: { // each tick mark is technically a Line shape with a label
    labelConfig: {
      fontFamily: "serif",
      fontMax: 100
    }
  },
  titleConfig: {
    fontFamily: "serif",
    fontMax: 100
  }
})
```

If that still doesn't work, please post an issue in [d3plus-plot](https://github.com/d3plus/d3plus-plot) with a jsfiddle. 👍
