### ISSUE TITLE
Disable legend for Treemap

### ISSUE THREAD

**Issue by alexandermeindl** [alexandersimoes/d3plus#633]
Is it possible to disable the legend for Treemap in v2? In our use case we have over 1000 entries without grouping. The best solution for us would be, to disable legend.

**Comment by davelandry** [comment]
@alexandermeindl yup, use the [legend](http://d3plus.org/docs/#Viz.legend) method:

```js
new d3plus.Treemap()
  .legend(false);
```

**Comment by alexandermeindl** [comment]
Thanks, it worked!
