### ISSUE TITLE
viz line chart not connect point

### ISSUE THREAD

**Issue by filmcup** [alexandersimoes/d3plus#635]
if i config "ticks": [] to x axis line not show but show point of data and when remove  "ticks": [] is work fine. what i wrong?
.x({"value":"time", zerofill: true, "ticks": []})

example my code and data
https://jsfiddle.net/rd5bxeyb/

Thank.

**Comment by davelandry** [comment]
Hi @filmcup, I've simplified your code, and this seems to work: https://jsfiddle.net/rd5bxeyb/3/
