### ISSUE TITLE
How to put an image/icon in Treemap chart(Inside the label boxes)

### ISSUE THREAD

**Issue by sauryanjanbhoi** [alexandersimoes/d3plus#637]
Hi,
Treemap has multiple divisions. I want to add image inside a division on click event.
Is there some feature like this or work around.

Thanks

**Comment by davelandry** [comment]
The new 2.0 modules support this, I've created an example showing how to set a background image: http://d3plus.org/examples/d3plus-hierarchy/background-image/

**Comment by TsengTofu** [comment]
Sorry, I'm new to d3plus, can I use version 1.0 to add image on the nodes?
Or only can do it in version 1.0?
Thanks.
