### ISSUE TITLE
Timeline Play Button not working without Internet Access

### ISSUE THREAD

**Issue by Wils0751** [alexandersimoes/d3plus#639]
I am currently trying to run a d3Plus graph without internet access. I have downloaded a local copy of the d3Plus Library, however when I go to use it in my Project the play button display's as this: ▢ .
Does anyone else have this issue?

Perhaps the Play/Pause button is linking to an online copy of Font-Awesome?

Here is a picture of what is happening

![image](https://user-images.githubusercontent.com/14221624/39259408-52e0b498-4884-11e8-8b61-d17fd1aafc7f.png)

Anyone who know's a workaround or where I can change in the source code to link the icon would be greatly appreciated.

**Comment by Wils0751** [comment]
@davelandry I found this shortly after posting the issue, it read like this when I first found it

```
.timeline({
play: { 
icon: { 
awesome: "□", 
fallback: ">", 
},
 pause: { 
awesome: "□", 
fallback: "||", 
} 
} 
})
```

After changing the awesome icon to the same as the fallback it seemed to be working. I am unsure why the square was the default.

**Comment by davelandry** [comment]
It renders as a square if you do not have the font-awesome font family installed on your computer, but should work in browser if you are loading the font-awesome css.
