### ISSUE TITLE
Timeline for Bar Chart 

### ISSUE THREAD

**Issue by bethgreenephd** [alexandersimoes/d3plus#644]
Hi—this is almost certainly a dumb question, but I've been over the d3 plus website, and I can't find an answer. I am making a bar chart of population projections, and I'd like to be able to have the user select the year and have the data filter accordingly. I've seen the v1 example (here: http://d3plus.org/examples/advanced/10754920/), but can't find how I would do this in v2. Is there a way to do this? Thanks!

**Comment by davelandry** [comment]
@bethgreenephd you probably need to set the time method. For example, if your data rows look like this:

```js
{value: 10, date: "06/12/1987", id: "alpha"}
```

Then you would need to set this on your visualization:

```js
.time("date")
```

**Comment by davelandry** [comment]
@bethgreenephd if it's still not working, please share your code so we can help debug. [JSFiddle](http://jsfiddle.net/) is great for creating live examples.
