### ISSUE TITLE
Map Points Not Resizing

### ISSUE THREAD

**Issue by bethgreenephd** [alexandersimoes/d3plus#646]
Hi—me again with a different chart. This time, when I do a Geomap and I resize, the map points aren't going into the right place--they only do so if I refresh the page or zoom in. Here's the code: 

http://jsfiddle.net/srbuy7ez/

Thanks so much for all your help!

**Comment by davelandry** [comment]
Thanks for reporting this @bethgreenephd! I've moved this into the d3plus-geomap repository: https://github.com/d3plus/d3plus-geomap/issues/20
