### ISSUE TITLE
Can I override the default css?

### ISSUE THREAD

**Issue by SeloSlav** [alexandersimoes/d3plus#647]
Hi,

I was wondering if was possible to override the default css, and if so what is the standard method to do so? One thing I wanted to do in particular was remove the white "fill" when rendering the main rect to a div. Of course, I would also like to change the font of the labels and the background colors of the data bubbles. Is there a general way to do this?

Current: 
![image](https://user-images.githubusercontent.com/8828948/42480656-5f9d000c-8393-11e8-9eb6-91b3835b8d1c.png)

Desired Outcome:
![image](https://user-images.githubusercontent.com/8828948/42480680-86e13bba-8393-11e8-9faf-f1c25b99b0f9.png)

**Comment by davelandry** [comment]
@SeloSlav of course! Take a look at [this page](https://github.com/alexandersimoes/d3plus/wiki/Visualizations), which documents all of the available methods (`.background("transparent")` will remove the background).

Additionally, there are a bunch of examples [here](http://d3plus.org/examples/1.0/) which show how to use a lot of the features. To get you started, [this one](http://d3plus.org/examples/advanced/3f0469cab1778d01c508/) shows how to supply custom colors.
