### ISSUE TITLE
Treemap window resize

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#651]
Hello, I´ve created a html which has radiobuttons to control the d3plus treemps, according to the selection it should show a graph, it works ok, the problem is when the size of the screen changes, when it happens the graphic which is not selected is not showed completely. Anyone could help me?.  The code is the following:

CSS:
.cont{
		margin: 0;
		bottom: 0;
		position: absolute;
		top: 0px;
		left: 0px;
		width: 100%;
		height: inherit;
	}

html:
<div style="width: 10%; float: left;">
	<label><input onclick="switchChart('cont16')" type="radio" name="type" checked>2016</label> <br>
	<label><input onclick="switchChart('cont15')" type="radio" name="type">2015</label> <br>
</div>

<div style="width: 90%; height:inherit; float: right; position: relative;">
<div id="cont15" class="cont"><div id="viz1" style="width:inherit; height:inherit;"></div></div>
<div id="cont16" class="cont"><div id="viz" style="width:inherit; height: inherit;"></div></div>

</div>

JS:
d3.csv("todos.csv", function(error, data) {
    data.forEach(function(d){
        d.id = d.id;
        d.d2016 = +d.d2016;
		d.color = d.color;
    });

    sdata = data;
	new d3plus.Treemap()
    .data(sdata)
    .groupBy(["id"])
    .sum("d2016")
	.select("#viz")
    .render();
	
	new d3plus.Treemap()
    .data(sdata)
    .groupBy(["id"])
    .sum("d2015")
	.select("#viz1")
    .render();
	
   });

function switchChart(cont){
    containers = document.getElementsByClassName("cont");
    for (i = 0; i < containers.length; i++) {
        containers[i].style.display = 'none';
    }    
    document.getElementById(cont).style.display  = 'block';
};

**Comment by ranucame** [comment]
I've created the JSFiddle (https://jsfiddle.net/ranucame/tLcge8bq/21/) but
it soesn't work, I tried several ways but without any result.

Regarding the use of .sum(), it could be something like this:

.sum(switch)

function switch(cont){
if(cont=="2016"){ return "d016"};
if(cont=="2015"){ return "d015"};
}

Thanks

**Comment by davelandry** [comment]
Check out this solution: https://jsfiddle.net/tLcge8bq/53/

**Comment by ranucame** [comment]
Thank you so much. An aditional question, for this treemap, how can modify
the size of the legend and remove the texts?

Sorry but I am new using D3plus.

**Comment by davelandry** [comment]
The `.legendConfig` method provides access to all the methods for the `Legend` class: https://jsfiddle.net/tLcge8bq/55/

Full documentation here: http://d3plus.org/docs/#Legend

**Comment by davelandry** [comment]
@ranucame you just need to define the `.time()` variable. In order to use the internal timeline behavior, d3plus expects a different data point for each year (not individual keys in the same object). So given data that looks like this:

```js
var data = [
  {id: "alpha", value: 4, year: 2016},
  {id: "alpha", value: 5, year: 2017},
  ...
];
```

You would set this method to tell d3plus about which key corresponds with time:

```js
.time("year")
```
