### ISSUE TITLE
Pareto Chart

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#656]
Hello, I would like to know if it is possible to draw a Pareto Chart

Thank you

**Comment by davelandry** [comment]
All shapes supported by [d3plus-shape](https://github.com/d3plus/d3plus-shape/#api-reference) can be drawn on a [Plot](http://d3plus.org/examples/d3plus-plot/bubble-plot/). The **.shape()** method can be set to defined different shapes for different data points:

```js
.shape(d => d.id === "alpha" ? "Bar" : "Line")
```

Additionally, custom [annotations](http://d3plus.org/examples/d3plus-plot/annotations/) can also be added.

@ranucame if you need further help, please post a link to a JSFiddle with some sample data and a first stab at trying to create your chart.

**Comment by ranucame** [comment]
Hi Dave, sorry for the inconveniences. I'vre created a JSFiddle:

https://jsfiddle.net/ranucame/r6804ov5/15/

I have two questions:
1. How can use different colors for the bars, I've tried changing the fill in ShapeConfig but it doesn't work.
2. The item1, item2 doesn't have value1, I mean it is "null", so, the circle shouldn't be showed. How can disappear the circles of item1 and item2.

Thank you

**Comment by davelandry** [comment]
Here's an updated fiddle: https://jsfiddle.net/r6804ov5/17/

1. You were so close! The methods in d3plus can only be passed 1 object. Take a look at the shapeConfig in my example.
2. You can set custom configs for individual shapes be nesting them in an Object with that shape name. Take a look at the shapeConfig in my example, I'm setting the `r` property of the circles based on the `value1` data point.

**Comment by ranucame** [comment]
Thank you for your anser. Just one question, is there some way to align the
0s of the y and y2 axis?

**Comment by davelandry** [comment]
a combination of removing the `value1` data from "alpha", removing the `value` data from "delta", and setting `.baseline(0)`: https://jsfiddle.net/r6804ov5/20/

**Comment by ranucame** [comment]
thank you!
