### ISSUE TITLE
question about xSort function

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#658]
Hello,

I have a BarChart in this link:
http://jsfiddle.net/ranucame/f52hLnx3/3/

I want order the items, but when I use .xSort((a, b) => a.x - b.x) (which is with //) the chart is showed wrongly.
What is the mistake?

Thanks

**Comment by davelandry** [comment]
what output are you expecting? if you are trying to show bars in ascending/descending order, you need to sort based on the Y: http://jsfiddle.net/f52hLnx3/5/

also, please label issues with more descriptive titles.

**Comment by ranucame** [comment]
sorry for the inconveniences.

Thank you so much
