### ISSUE TITLE
Annotations in Donut chart

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#660]
Hello,

I'd like to know if I can use "Annotations" to include a text in the middle of the donut chart

![pie](https://user-images.githubusercontent.com/42725078/45581643-b0abee00-b867-11e8-971b-14b2d9d9e887.png)

This is my JSFiddle
http://jsfiddle.net/ranucame/wryzho7L/2/

Thanks

**Comment by davelandry** [comment]
Moved feature request to `d3plus-hierarchy`: https://github.com/d3plus/d3plus-hierarchy/issues/44
