### ISSUE TITLE
Long labels in horizontal bar chart

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#662]
Hello,

In the case of long labels in the axis, is it possible set the them in two or three lines to have more space for the chart?

Check my Jsfiddle
http://jsfiddle.net/ranucame/wm5qL1e3/2/

Thanks

**Comment by davelandry** [comment]
Currently, the y-axis labels cannot be text wrapped (I've created an issue [here](https://github.com/d3plus/d3plus-axis/issues/68)). In cases like yours, I generally place the labels directly inside the bars (which does have text-wrapping): http://jsfiddle.net/wm5qL1e3/4/

**Comment by ranucame** [comment]
Thank you!
