### ISSUE TITLE
Change tooltip of legend

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#663]
Hello, I have a bar chart (http://jsfiddle.net/ranucame/9zthwx4r/3/), I was trying to hide some items of the tooltip in the legend, because in the current version shows all the values.

is tehre some way to do it?

Thanks

**Comment by davelandry** [comment]
@ranucame the legendTooltip method allows you to override the behavior of the tooltips in the legend. Additionally, you may be interested in the `tbody` method which helps making tables in the tooltips a bit easier: http://jsfiddle.net/9zthwx4r/7/
