### ISSUE TITLE
d3plus v2 export

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#664]
Hello,
one question , is it possible to use the functions export to download the charts as csv, png, etc in D3plus v2?

Thanks

**Comment by davelandry** [comment]
absolutely, that's what the `d3plus-export` library is built for: https://github.com/d3plus/d3plus-export#api-reference

**Comment by ranucame** [comment]
Hi Dave,

I was trying to do it, but I coulnt get it (
http://jsfiddle.net/ranucame/vstc93ga/10/), I have to define "ui" and use
"saveElement" as method?

Thanks

**Comment by davelandry** [comment]
There's actually a method that puts a `downloadButton` in the visualization for you: http://jsfiddle.net/vstc93ga/12/

**Comment by ranucame** [comment]
Thank you! just one more question, how can change the font, color and others features of the button, I've tried using downloadConfig, but it doesn't work.

Thanks

**Comment by davelandry** [comment]
```js
.controlConfig({buttonConfig: { /* any valid css */ }})
```

for example:
```js
.controlConfig({buttonConfig: {"font-family": "Comic Sans MS"}})
```

**Comment by ranucame** [comment]
Thank you

**Comment by ranucame** [comment]
sorry, for the inconvenience, I was trying to change the background and color of the button, but it doesn't work: http://jsfiddle.net/vstc93ga/12/
what is the mistake?

**Comment by davelandry** [comment]
My apologies, it's `buttonStyle` not config: http://jsfiddle.net/vstc93ga/16/

**Comment by ranucame** [comment]
Thank you Dave.
How can modify the text of the button? I was trying with "value" but it
doesn't work

https://jsfiddle.net/ranucame/kju0cv2r/2/

Also, what is the equivalent to the function "background" of the version 1
to change the background of the chart?

Thank you

**Comment by davelandry** [comment]
@ranucame right now, the text inside of the button is not changeable and the chart background color is not configurable.

**Comment by ranucame** [comment]
I see, thank you.

How can Include a button to download the chart info as csv?

Thanks

**Comment by davelandry** [comment]
@ranucame that functionality has not been built internally. In some of my other projects I've created custom buttons and used the `saveAs` function within the [`file-saver`](https://github.com/eligrey/FileSaver.js/) package.

**Comment by ranucame** [comment]
Thank you
