### ISSUE TITLE
Treemap tooltip - Percentage value

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#665]
Hi, one question

how can add the percentage value to the tooltip?

http://jsfiddle.net/ranucame/0y9ku3vz/

Thanks

**Comment by davelandry** [comment]
@ranucame that's a great idea to have in there by default, so I've [made an issue](https://github.com/d3plus/d3plus-hierarchy/issues/46) specific to the hieararchical visualizations. In the meantime, here's your updated fiddle, which also utilizes the `tbody` configuration that makes making the table easier: http://jsfiddle.net/0y9ku3vz/1/

**Comment by ranucame** [comment]
Thank you
