### ISSUE TITLE
Timeline location

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#666]
Hello,

is possible to make that the timeline is showed at the begin of the container and not at the begin of the axes (http://jsfiddle.net/71fn60ve/)?

Thanks

**Comment by davelandry** [comment]
Unfortunately no, not at this time. This is the intended behavior (centering underneath the chart). This would have to be added to [d3plus-viz](https://github.com/d3plus/d3plus-viz/) as a toggle-able option.

**Comment by ranucame** [comment]
thank you Dave
