### ISSUE TITLE
Chart - Render as image

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#668]
Hello,

is there some way to render a chart directly as an image (png or jpg) and not as SVG?

Thanks

**Comment by davelandry** [comment]
@ranucame the default downloadButton saves to PNG: http://jsfiddle.net/tm9xpswe/6/

**Comment by ranucame** [comment]
My explanation was not good. I am trying to make a pdf with some D3 plus
charts, but I need the charts as image to be processed by the other library
and generate the pdf. For this reason, I want to know if it is possible to
render the chart as image and not as a svg.

**Comment by davelandry** [comment]
@ranucame what file format are you trying to get? You keep saying "image", and that's what the default export (PNG) is.

**Comment by ranucame** [comment]
is PNG
