### ISSUE TITLE
Timeline listening

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#671]
Hello,

I have a question, is possible to add a listener to the timeline to show a different value as a tittle when the time selector changes. Please check my jsfiddle (https://jsfiddle.net/ranucame/s7n9a401/12/)

Thanks

**Comment by davelandry** [comment]
https://jsfiddle.net/9pq1cgu4/

**Comment by ranucame** [comment]
Sorry Dave, I checked your code but the console doesn't show the value of the time-line, something is missing?

**Comment by davelandry** [comment]
It defaults to the latest value in the dataset, and that function is triggered when you click onto a new value in the timeline. If you click "2010" in the timeline, you should see this in the console: `Fri Jan 01 2010 00:00:00 GMT-0500 (Eastern Standard Time)`
