### ISSUE TITLE
d3plus barchart loads again on page scroll [Mobile]

### ISSUE THREAD

**Issue by sureshselvaraj** [alexandersimoes/d3plus#680]
d3plus.BarChart() and d3plus.Treemap() rerenders again on page scroll in mobile browsers. This happens when the user touch and scrolled on the graph in mobile. The graph reloads again and again.

**Comment by davelandry** [comment]
@sureshselvaraj can you share an example of this behavior? show us how you constructed your code

**Comment by sureshselvaraj** [comment]
new d3plus.BarChart()
        .select('#' + id)
        .data(data)
        .stacked(is_stacked)
        .stackOrder(["Beverage", "Available Co2", "Food", "Industry", "In Transit", "Empty"])
        .barPadding(0)
        .shapeConfig({
            hoverOpacity: 1,
            stroke: function (d) {
                if (tooltipData.stroke) {
                    return tooltipData.stroke.strokeColor
                }
                return ''
            },
            strokeWidth: function (d) {
                if (d.id == 'Total Capacity') {
                    return '0px'
                }
                if (tooltipData.stroke) {
                    return tooltipData.stroke.strokeWidth
                }
            },
            fill: function (d) {
                return barColor[d.id];
            },
            Bar: {
                labelConfig: barLabelConfig,
                label: function (d) {
                    if (is_stacked) {
                        if (d.id == "Empty" && d.y >= 0) {
                            return tooltipData.labelData[d.x]
                        }
                        else if (d.id == "In Transit" && d.negative) {
                            return tooltipData.labelData[d.x]
                        }
                        else if (d.id == "Industry" && tooltipData.negativeData[d.x]) {
                            return tooltipData.labelData[d.x]
                        }
                         else {
                            return sumproduction[d.x];
                         }

                        if (d.id == "withOutOrder") {
                            var res = 0;
                            $.each(eveningResponse, function (index, value) {
                                if (value.id == "withOutOrder" && value.x == d.x) {
                                    res = eveningResponse[d.y].y;
                                    // console.log(res);
                                }
                            })
                            return res;
                        }
                    } else {
                        if (d.y == 0) {
                            return d.y
                        } else {
                            return d.y;
                        }
                    }
                },
            }

        })
        .tooltipConfig({
            body: function (d) {
                if (tooltipData.showAllGrades) {
                    var obj = {}
                    var legend = false;
                    Array.prototype.forEach.call(data, function (d1) {

                        if (d1.x == d.x) {
                            if (d1.id == 'Empty') {
                                obj[d1.id] = d1.yNeg ? d1.yNegValue : d1.percent90Cap
                            }
                            else
                                obj[d1.id] = d1.y
                        } else {
                            if (d.id == 'Empty')
                                obj[d.id] = d.yNeg ? d.yNegValue : d.percent90Cap
                            else
                                obj[d.id] = d.y

                        }
                    })
                    var table = '<table class="dashboard-font" style="box-shadow:none;border:none !important">'
                    var others = true;
                    if (obj["Beverage"]) {
                        others = true;
                        if (!legend)
                            table += '<tr><td><div class="indicate" style="background-color:' + barColor["Beverage"] + '"></div></td><td> Beverage</td><td>: ' + obj["Beverage"] + '</td></tr>'
                        else
                            table += '<tr><td> Beverage</td></tr>'
                    }
                    if (obj["In Transit"]) {
                        others = true;
                        if (!legend)
                            table += '<tr><td><div class="indicate" style="background-color:' + barColor["In Transit"] + '"></div></td><td> In Transit</td><td>: ' + obj["In Transit"] + '</td></tr>'
                        else
                            table += '<tr><td> In Transit</td></tr>'
                    }
                    if (obj["Food"]) {
                        others = true;
                        if (!legend)
                            table += '<tr><td><div class="indicate" style="background-color:' + barColor["Food"] + '"></div></td><td> Food</td><td>: ' + obj["Food"] + '</td></tr>'
                        else
                            table += '<tr><td> Food</td></tr>'
                    }
                    if (obj["Industry"]) {
                        others = true;
                        if (!legend)
                            table += '<tr><td><div class="indicate" style="background-color:' + barColor["Industry"] + '"></div></td><td> Industrial</td><td>: ' + obj["Industry"] + '</td></tr>'
                        else
                            table += '<tr><td> Industrial</td></tr>'
                    }
                    if (obj["Available Co2"]) {
                        others = true;
                        if (!legend)
                            table += '<tr><td><div class="indicate" style="background-color:' + barColor["Available Co2"] + '"></div></td><td> Available Co2</td><td>: ' + obj["Available Co2"] + '</td></tr>'
                        else
                            table += '<tr><td> Available Co2</td></tr>'
                    }
                    if (obj["Empty"]) {
                        others = true;
                        if (!legend) {
                            if (obj["Empty"] < 0) {
                                table += '<tr style="color:red"><td><div style="background-color:white"></div></td><td> EXCEED</td><td>: ' + Math.abs(obj["Empty"]) + '</td></tr>'
                            }
                            else
                                table += '<tr><td><div class="indicate" style="background-color:' + barColor["Empty"] + '"></div></td><td> Unfilled</td><td>: ' + obj["Empty"] + '</td></tr>'
                        }
                        else
                            table += '<tr><td> Vacant</td></tr>'
                    }
                    if (obj["Total Capacity"] >= 0 && Object.keys(obj).length == 1) {

                        table += '<tr><td> Capacity of a unit </td></tr>'
                    }


                    table += '</table>'
                    return table;
                } else {
                    if (tooltipData.position == 'before') {
                        return tooltipData.units + d.y;
                    }
                    else if (tooltipData.position == 'after') {
                        return d.y + tooltipData.units;
                    } else if (tooltipData.position == 'doubleBarAfter') {
                        if (d.id == tooltipData.id0) {
                            return d.y + tooltipData.commonUnit + tooltipData.units0;
                        }
                        if (d.id == tooltipData.id1) {
                            return d.y + tooltipData.commonUnit + tooltipData.units1;
                        }
                    } else if (tooltipData.position == 'doubleBarBefore') {
                        if (d.id == tooltipData.id0) {
                            return tooltipData.units0 + d.y + tooltipData.commonUnit;
                        }
                        if (d.id == tooltipData.id1) {
                            return tooltipData.units1 + d.y + tooltipData.commonUnit;
                        }
                    } else if (tooltipData.position == 'beforeAfter') {
                        if (d.id == "Empty") {
                            // return "Vacant: " + numberWithCommas(d.y) + tooltipData.unitsAfter0;
                            return "<span >Unfilled: </span>" + numberWithCommas(d.y);
                        }
                        if (d.id == "Beverage") {
                            return "Beverage: " + numberWithCommas(d.y);
                        }
                        if (d.id == "In Transit") {
                            return "In Transit: " + numberWithCommas(d.y);
                        }
                        if (d.id == "Food") {
                            return "Food: " + numberWithCommas(d.y);
                        }
                        if (d.id == "Industry") {
                            return "Industrial: " + numberWithCommas(d.y);
                        }
                        if (d.id == "Available Co2") {
                            return "Available Co2 : " + numberWithCommas(d.y);
                        }
                        if (d.id == "Total Capacity") {
                            // return "Max. Capacity: " + tooltipData.replaceData["Total Capacity Value"]  ;
                            return "Capacity of a unit";
                        }
                    }
                }
            },
            title: function (d) {
                var tot = 0;
                try {
                    Array.prototype.forEach.call(tooltipData.totalStock, function (data) {
                        if (data.branch == d.x) {
                            tot = data.totalStock;
                        }
                    })
                    var txt = d.x;
                    return '<span class="dashboard-font">' + txt.toUpperCase() + ' - ' + numberWithCommas(tot) + ' </span>';

                } catch (error) {
                }
            }
        })
        .xConfig({
            shapeConfig: {
                labelConfig: {
                    height: 20,
                    // width:10,
                    fontMin: 5,
                    fontMax: 12,
                    fontResize: true,
                    fontColor: 'white',
                },
                label: function (d) {
                    return d.text;
                },
                labelBounds: function (d, i, shape) {
                    return d.labelBounds;
                }
            },
            titleConfig: {
                fontMax: 100,
            },
        })
        .yConfig({
            barConfig: { stroke: "black", strokeWidth: '2' },
            gridConfig: { stroke: "#61666a" },
            shapeConfig: {
                labelConfig: {
                    height: 20,
                    fontMin: 10,
                    fontResize: true,
                    fontColor: 'white',
                },
                label: function (d) {
                    return d.id;
                },
                labelBounds: function (d, i, shape) {
                    return d.labelBounds;
                }
            },
            titleConfig: {
                fontMax: 100,
            },

        })
        .legend(false)
        .legendConfig({
            "label": function (d) {
                if (tooltipData.replaceLegendName) {
                    return tooltipData.replaceData[d.id]
                } else {
                    return d.id
                }
            },
            shapeConfig: {
                height: function (d) {
                    if (d.id == 'Total Capacity') {
                        return 2
                    }
                    return 10
                },
                width: 10,
                ariaLabel: function (d) {
                    console.log(d);
                },
                labelConfig: {
                    fontColor: "white"
                },
                fontMin: 20,
                fontMax: 100,
                fontResize: true,
                barConfig: function (d) {
                    console.log(d);
                }
            }
        })
        .legendTooltip(false)
        .legendPosition("top")
        .loadingHTML(`
        .annotations([{
            data: function (d, i) {
                if ('annotaionProperties' in tooltipData) {
                    annotationShapeColor = "red"
                    var thresholdArray = [];
                    Array.prototype.forEach.call(tooltipData.threshold, function (thresholdData) {
                        if (thresholdData.enabled)
                            thresholdArray.push({ x: thresholdData.region, y: (thresholdData.fillingCapacity) , width: divWidth / 50, height: 1 })
                    })
                    return thresholdArray;
                }
                else {
                    annotationShapeColor = "transparent"
                    return [];
                }
            },
            shape: "Rect",
            stroke: annotationShapeColor,
            strokeWidth: 1
        }])
        .render(interval);

**Comment by sureshselvaraj** [comment]
https://drive.google.com/open?id=1EnMbQcWChSJlvkWyby2IDg_Om19_Rw24 : Attached the link to the video describing the issue. This was done in ipad device. Same issue recurs in mobile devices too. In desktops, it is working fine.

**Comment by davelandry** [comment]
Good find @sureshselvaraj. I can confirm that I've observed the bug. I've moved the issue here: https://github.com/d3plus/d3plus-viz/issues/108, which is where the scroll detection happens.
