### ISSUE TITLE
Bug in bar chart axis labels

### ISSUE THREAD

**Issue by akimbekov** [alexandersimoes/d3plus#682]
There's a small bug in a bar chart. 
The problem I was trying to solve is to not show axis labels.
To do that, I tried two approaches:
1. label x-axis with space (" ")
+ this plot makes sense
2. label x-axis with an empty string ("")
+ this plot does not make sense at all

Try the code below:

`
//try x: "" instead of x: " " 
 var data = [
  {id: "alpha", x: " ", y:  7},
  {id: "beta", x: " ", y: 5},
  {id: "gamma",  x: " ", y: 1}
  ];

new d3plus.BarChart()
  .data(data)
  .stacked(false)
  .height(500)
  .width(300)
  .legend(false)
  .shapeConfig({
    Bar: {
      labelConfig:{
          fontFamily: "serif",
          fontSize: 20,
          textAnchor: "middle",
          verticalAlign: "middle",
          fontColor: "white"
        }
      }
    })
  .shapeConfig({
    label: function (d) {return d.y}
  })
  .render();`

**Comment by davelandry** [comment]
There needs to be a unique value in your data that determines how to separate the data across the x-axis. In your case, if you want to use the "id" property for the x-axis, then you should set `.x("id")`.

If you want to hide the x-axis ticks, you can go into the config for the x-axis using the [`xConfig`](https://github.com/d3plus/d3plus-plot/#Plot) method, which gives you full access to all of the methods for the [`Axis`](https://github.com/d3plus/d3plus-axis/#Axis) constructor that is used to generate the x-axis:

```
.xConfig({
  ticks: [] // an array of the tick marks that should be shown
})
