### ISSUE TITLE
Viz.groupBy() Function Duplicating Data in Treemap

### ISSUE THREAD

**Issue by WSBenson** [alexandersimoes/d3plus#685]
In version 1.0 of d3plus, the Viz.id() function was used to created a hierarchical tree map visual in which you could navigate through a group and its sub-groups by clicking on the different tiles.

With the update to 2.0, the new function to do this seems to be Viz.groupBy(). I created an html file (attached in the .zip) to test the functionality of the Viz.groupBy() function and found that it was exhibiting some strange behavior when you navigated to the last group in the treemap. Sometimes it wouldn't display certain information, and when it did display information... it duplicated it. Is this an issue somewhere or am I missing something?

**Image of duplicate behavior:**
![duplicate](https://user-images.githubusercontent.com/51492428/59130386-50049a00-893d-11e9-94fd-c82ae23be8ae.PNG)

As you can see, it shows the ranch group twice (after clicking on ranch) and is missing a tile for the "A Lot" Amount group.

**zip file with the html file in it:**
[test.zip](https://github.com/alexandersimoes/d3plus/files/3267406/test.zip)

**Comment by davelandry** [comment]
@WSBenson thanks for posting this bug! I've confirmed that this is not the intended behavior, and made an issue here: https://github.com/d3plus/d3plus-viz/issues/125
