### ISSUE TITLE
multiple line annotations not working

### ISSUE THREAD

**Issue by mwolfeu** [alexandersimoes/d3plus#686]
When modifying the example:
https://d3plus.org/examples/d3plus-plot/area/

Multiple "line" shapes in the annotations array just draws the last one.
Ex:
{
      data:[{x:5, y:0},{x:5, y:25}],
      shape: "Line", 
      stroke: "#000",
      strokeDasharray: "10", 
      strokeWidth: 4  
    },
    {
      data:[{x:6, y:0},{x:6, y:25}],
      shape: "Line", 
      stroke: "#000",
      strokeDasharray: "10", 
      strokeWidth: 4  
    }

**Comment by davelandry** [comment]
Moved to https://github.com/d3plus/d3plus-plot/issues/142
