### ISSUE TITLE
datapoint hover functionality 

### ISSUE THREAD

**Issue by mwolfeu** [alexandersimoes/d3plus#688]
When you hover over/near datapoints and get the horizontal/vertical line you can get the tooltip as in this v1 example:
http://d3plus.org/examples/basic/9037371/

Does this functionality exist in v2?
For area charts?

If so, what should I be looking at?

**Comment by davelandry** [comment]
Still needs to be implemented in 2.0: https://github.com/d3plus/d3plus-plot/issues/139
