### ISSUE TITLE
d3plus v2: "Radar" chart not included in full release

### ISSUE THREAD

**Issue by brannie19** [alexandersimoes/d3plus#690]
Hello!

I've noticed that the Radar chart class is completely missing from the full alpha release JS file:
https://d3plus.org/js/d3plus.v2.0.0-alpha.23.full.min.js
It's also missing from https://d3plus.org/js/d3plus.v2.0.0-alpha.24.full.min.js

I noticed it has been added to the d3plus-plot module.

Is there any change it will be added in the next week or so?
I need to use it for a project I'm currently working on.

Thank you!

**Comment by davelandry** [comment]
@brannie19 should be fixed with https://d3plus.org/js/d3plus.v2.0.0-alpha.25.full.min.js

I wrote a test script that ensures all available functions and classes are exporting from each module, found a few other ones that were missing as well 😎
