### ISSUE TITLE
Does it exist version of python packages?

### ISSUE THREAD

**Issue by Xelawk** [alexandersimoes/d3plus#692]
I just want to run the computation code to find  the largest rectangle in a given non-convex polygon. Do you have any version of python to do it. Thanks!

**Comment by davelandry** [comment]
Unfortunately no, d3plus is a JavaScript library and the largest rectangle code was written from scratch. The latest version of the code is here: https://github.com/d3plus/d3plus-shape/blob/master/src/geom/largestRect.js
