### ISSUE TITLE
Set highlight on chart load?

### ISSUE THREAD

**Issue by richhauck** [alexandersimoes/d3plus#693]
Is there a way to define highlight when the chart first renders? I am basically looking for the same behavior as when clickLegend() is called and a certain data set is displayed while another is hidden.

**Comment by davelandry** [comment]
hmm, this is a really cool idea. I just tried to do/hack it, but it'll need some internal work

**Comment by davelandry** [comment]
moved to https://github.com/d3plus/d3plus-viz/issues/142
