### ISSUE TITLE
Accessibility page duplicate content

### ISSUE THREAD

**Issue by iSamMitchell** [alexandersimoes/d3plus#694]
On `/accessibility` there is duplicate content.

```SVG "role" - All SVG elements created by D3plus contain a role attribute with the value "img". This ensures that all visualizations are identified as a graphic.``` is repeated two lines later in the first bulleted list.

https://d3plus.org/accessibility/
<img width="789" alt="Screen Shot 2020-03-12 at 2 05 41 PM" src="https://user-images.githubusercontent.com/17798017/76553531-96f26380-646a-11ea-93d6-13aa3b6ba3e1.png">

**Comment by davelandry** [comment]
Good catch @iSamMitchell, thanks for reporting!
