### ISSUE TITLE
Treemap Timeline selecting Year in JS

### ISSUE THREAD

**Issue by xscotta** [alexandersimoes/d3plus#696]
I am using D3plus v2.0.0-alpha.25 (Dec 11 2019), That is what is says in the comments of the file.

I created a treetmap with "Year" as a value in the .Time("Year"), this works great, it created a legend that I could choose to change the Year being viewed, but I wish to set the starting value rather than it default to the latest value.

What is the correct way to specify that? from the documentation it implies .selection(value) or .selectionConfig(value).

I tried .selectionConfig(2019)  and  .selection(2019) but they didn't have any effect

Thanks in advance, if you have a link to a working example that would be great.

**Comment by xscotta** [comment]
P.S I am using "new d3plus.Treemap" to render the viz, works well, just need to override the starting .time value, which from my CSV file is a field called "Year" values 2018, 2019, 2020 etc.
.
.
new d3plus.Treemap()
  .data(data)
  .groupBy(["Desc1","Desc2"])
  .depth(0)
  .sum("Spend")
  .time("Year")
  .timelineConfig({
    buttonHeight:20,
    buttonPadding:20
    })
  .select("#viz")
  .render();

**Comment by davelandry** [comment]
@xscotta you're looking for the `timeFilter` method, which is an accessor function that is provided the data point and expects a `true`/`false` return. Check out his example: https://jsfiddle.net/censgtj5/

```js
  .timeFilter(function(d) {
    return d.Year === 2019;
  })
```

**Comment by xscotta** [comment]
Thank you, that worked a treat. Is there a way to see which "Year" value is selected by the user? say if they selected 2018 or 2020 can I see or test for that? Thanks in advance, happy to create a new question for this.
