### ISSUE TITLE
obtaining the value selected by user on timeline

### ISSUE THREAD

**Issue by xscotta** [alexandersimoes/d3plus#697]
I am displaying a Treemap for multiple years 2018, 2019, 2020. I start the display on 2019 using timeFilter, but if they then choose 2018 is there a way I can get access to, and see, that chosen value in JS?

When I log the event of clicking on the Year, it just shows the "rect" tag with the class "overlay", no particular values, which makes sense since they are displayed as text at this point.

new d3plus.Treemap()
    .data(data)
    .groupBy(["Desc1","Desc2"])
    .depth(0)
    .sum("Spend")
    .time("Year")
    .timeFilter(function(d) { return d.Year === 2019; })
    .select("#viz")
    .render();

**Comment by davelandry** [comment]
You're looking for the `on` events that map to the mouse events used by the d3-brush when selecting a date (or a range of dates). Listen for the `end` event, which is provided the finally selected date (as a JavaScript Date Object): https://jsfiddle.net/70n5a3wk/

```js
.timelineConfig({
  on: {
    end: function(d) {
      console.log(d);
    }
  }
})
```
