### ISSUE TITLE
Timeline cursor style

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#698]
Hello, 

I was trying to change the default option for the cursor "crosshair" in a timeline, is there some way to do that?

https://jsfiddle.net/ranucame/3csgtay9/4/

Thanks

**Comment by davelandry** [comment]
@ranucame yup! Take a look at this example: http://d3plus.org/examples/d3plus-timeline/change-style/

**Comment by ranucame** [comment]
Dave, I've used handleConfig and it is possible to change the style of the cursor of the handle, but if the mouse is over other part of the timeline the "crosshair" is still showed. Is it possible to change it?

**Comment by davelandry** [comment]
Ahhh I see what you mean. Unfortunately no, currently the behavior is hardcoded to be "crosshair" when brushing is allowed (selecting multiple time periods), and set to "pointer" if brushing is disabled. I've made [this issue](https://github.com/d3plus/d3plus-timeline/issues/61) for adding support to override this, and here's what it looks like with brushing disabled: https://jsfiddle.net/7qtfm1ub/

**Comment by ranucame** [comment]
Thank you!
