### ISSUE TITLE
Use of d3plus-export

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#699]
Hello, one question, is there an example about how to use d3plus-export to make a SVG or PNG file from a chart?

Thanks

**Comment by davelandry** [comment]
Good point, there isn't an example of how to do this currently. For now, I've made an issue for that: https://github.com/d3plus/d3plus-export/issues/9

In the meantime, here's an example of the usage. You're probably looking for the `saveElement` function:

```jsx
import {saveElement} from "d3plus-export";
```

The function primarily takes 2 arguments: the HTML dom element to be saved, and any additional options about the file: http://d3plus.org/docs/#saveElement

```jsx
saveElement(domElement, {filename: "my-chart", type: "png"})
```

**Comment by ranucame** [comment]
Hi Dave, I've tried to use the d3plus-export, please check this jsfiddle (https://jsfiddle.net/ranucame/g9ua0jm5/5/). What is missing/wrong?

**Comment by davelandry** [comment]
A few things:
1. you helped us find a bug in one of our polyfills for `innerHTML`! that's now been patched in the latest d3plus-export
2. you were passing a string to render like `.render("chart")`, but this should be `.select("#chart").render()`
3. my example code was for an ES6 environment that supports imports. for vanilla JS you still need to use the namespace of `d3plus.saveElement`

Check out this updated fiddle: https://jsfiddle.net/mx2oy438/1/

**Comment by ranucame** [comment]
Thank you Dave!
