### ISSUE TITLE
d3plus grouped barchart hides some lines on the x-axis

### ISSUE THREAD

**Issue by deveid** [alexandersimoes/d3plus#700]
d3plus grouped barchart hides some lines on the x-axis..The beginning and the ending lines on the barchart are hidden.How can I solve this
![image](https://user-images.githubusercontent.com/12122059/87655275-f1b90600-c74f-11ea-9584-c61f0033df17.png)

**Comment by davelandry** [comment]
Thanks for reporting this @deveid, this was one we've been trying to hunt down. Should be fixed now!
