### ISSUE TITLE
Bar chart & Treemap at the same page

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#703]
Hello, I am trying to render 2 charts, a bar chart and treemap but when use the two sources for them the console shows and error related with the constructors (https://jsfiddle.net/ranucame/y2rh3qs1/4/). 
What is wrong?
Thanks

**Comment by davelandry** [comment]
@ranucame looks like you can't include separate viz modules together (they must be overwriting eachother). Instead, use the compiled full d3plus library: https://jsfiddle.net/m6nuv1zf/

**Comment by ranucame** [comment]
Thank you!
