### ISSUE TITLE
BarChart Shapeconfig

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#704]
Hi, I want to know if in a horizontal stacked chart is possible to have just 1 label per bar and not 2 per each serie. Check my fiddle
https://jsfiddle.net/ranucame/o1n8szq9/17/

Also, how can locate the text on the left?

Thanks

**Comment by davelandry** [comment]
If you return `false` from the `label` function, then those labels won't be displayed.

The `yConfig` method gives access to the y-axis configuration, including the `ticks` array to show/hide certain ticks, and the `tickFormat` function to apply custom formatting to the labels.

Check out this updated config: https://jsfiddle.net/87pLq643/

**Comment by ranucame** [comment]
Thank you
