### ISSUE TITLE
Bar chart ID failure

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#706]
Hello,

I am making a bar char and if my data doesn't have the x value as "id" the chart shows the message undefined. Please check my fiddle (https://jsfiddle.net/ranucame/6dvcxae8/6/).

Thanks

**Comment by davelandry** [comment]
@ranucame you need to set the `groupBy` (which defaults to "id"): https://jsfiddle.net/hsra7f9g/1/

**Comment by ranucame** [comment]
Thanks
