### ISSUE TITLE
add support for power scales with custom exponent

### ISSUE THREAD

**Issue by xscotta** [alexandersimoes/d3plus#708]
I have used the following options to tease out more of the data when the difference between max/min is great.
.yConfig({ scale: "sqrt" }) — This applies a fixed exponent of 0.5 to the axis
.yConfig({ scale: "log" }) — This applies a natural log(e) to the axis

If I want to specify an exponent of 0.4 or 0.3, can I use "pow"? 
.yConfig({ scale: "pow" }) — And then specify the exponent somewhere?

The documentation on D3plus [http://d3plus.org/examples/d3plus-axis/scale-time/](http://d3plus.org/examples/d3plus-axis/scale-time/) says All of the scales made available by d3-scale are usable for an Axis by passing the name of the scale, in all lowercase, to the .scale( ) method.

Thanks for your help, I looked through the D3plus code and documentation but couldn't work it out.

**Comment by davelandry** [comment]
Good catch @xscotta. It seems that the d3plus axes don't currently support "pow" scales. I've moved this issue to the d3plus-axis repo: https://github.com/d3plus/d3plus-axis/issues/100
