### ISSUE TITLE
Create an example page for SVG word-wrapping

### ISSUE THREAD

**Issue by davelandry** [alexandersimoes/d3plus#80]

**Comment by aschriner** [comment]
I just ran into the same confusion as robross0606 about which element the `.container()` method takes as argument.  I'm also struggling to figure out how to apply this for multiple elements at once - or am I just supposed to iterate over them?

**Comment by davelandry** [comment]
Currently, you just have to iterate over each `<text>` element and call `d3plus.textwrap()` for each of them.

**Comment by ilbonte** [comment]
To iterate over each `<text>` you can use [.each] (https://github.com/mbostock/d3/wiki/Selections#each).
Example: 
```javascript 
d3.selectAll("text").each(function (d, i) {
            d3plus.textwrap()
                    .container(d3.select(this))
                    .draw();
        });
```

**Comment by guilhermecgs** [comment]
Can you provide an example of textwrap using shape with circle?

" If it can't find one, or that behavior needs to be overridden, they can manually be specified using .shape( ), .width( ), and .height( )."

**Comment by davelandry** [comment]
@guilhermecgs the radius of the circle would be half of the width/height. So, if you'd want a radius of 100px, you would say:

```js
.shape("circle")
.width(200)
.height(200)
```
